const translations = {
  zh: {
    "nav.services": "能力",
    "nav.categories": "方向",
    "nav.standards": "标准",
    "nav.training": "培训",
    "nav.cases": "案例",
    "nav.contact": "联系",
    "hero.eyebrow": "工业碳保证 · GHG核查/验证 · 二方/三方审核 · 科研合作",
    "hero.title": "面向工业企业与高校的碳保证、标准审核和科研转化平台",
    "hero.copy": "Enerstay Sustainability 聚焦工业碳保证、GHG verification / validation、ISO 管理体系二方/三方审核、培训课程、数字化 MRV 和科研知识产品。涉及正式核查或保证的项目严格区分培训、资料审阅与审核/核查角色。",
    "hero.calendly": "预约沟通",
    "hero.cta": "预约沟通",
    "hero.secondary": "查看能力",
    "stats.years": "工业项目连续经验",
    "stats.papers": "SCI/SSCI 论文与合作成果",
    "stats.standards": "覆盖GHG、ESG、能源与安全标准",
    "intro.kicker": "关于 Enerstay",
    "intro.title": "以工业碳保证、标准审核和科研产品连接低碳转型",
    "intro.copy": "Enerstay Sustainability Pte. Ltd. 注册于新加坡，定位为工业碳保证与专业标准平台，重点发展 NEA CPA evidence review、ISO 14064 / 14067、复杂行业高 GWP 气体、CBAM 数据、ESG 环境数据控制、二方/三方审核、高端培训、数字化 MRV、学术发表与标准化知识产品。",
    "founder.kicker": "谁在负责交付",
    "founder.title": "Dr. Strange 主理",
    "founder.copy": "Enerstay Sustainability 由 Dr. Strange 主理，连接新加坡碳监管、GHG verification / validation、ISO 管理体系审核、半导体高 GWP 气体与科研训练经验。涉及保证、核查或审核的工作，按独立性、利益冲突和授权范围进行边界管理。",
    "founder.point1": "NEA 碳定价法案相关核查与复杂行业经验",
    "founder.point2": "Applus+ 等企业合作与CBAM培训资源",
    "founder.point3": "SCI、SSCI、ESCI、EI 论文合作与科研训练",
    "founder.linkedin": "LinkedIn",
    "founder.scholar": "Google Scholar",
    "images.energy": "半导体洁净室与高GWP气体管理",
    "images.research": "科研训练与项目答辩",
    "images.training": "低碳能源与实施场景",
    "services.kicker": "Assurance, Training & Knowledge",
    "services.title": "工业碳保证、二方/三方审核与知识产品",
    "services.carbon.title": "GHG 核查/验证与保证证据审阅",
    "services.carbon.copy": "围绕 ISO 14064-1、ISO 14064-2、ISO 14064-3、ISO 14065、ISO 14066 的组织层面 GHG、项目减排量、验证/核查流程、证据抽样、重要性与结论边界开展二方或三方核查相关工作。",
    "services.esg.title": "ESG 环境数据控制与保证证据审阅",
    "services.esg.copy": "聚焦 ISSB / SGX 披露中的环境数据、Scope 3、供应商数据包、证据链、内部控制和保证证据审阅；不在同一项目中同时承担正式审核/保证结论与培训、科研活动。",
    "services.energy.title": "工业 MRV 与数字化证据链",
    "services.energy.copy": "审阅可核查的监测、报告与验证资料结构，覆盖活动数据、排放因子、设备记录、供应商资料、复核轨迹、异常处理和数字化证据包。",
    "services.material.title": "ISO 管理体系二方/三方审核",
    "services.material.copy": "针对 ISO 14001、ISO 45001、ISO 50001、Responsible Care 14001、ISO 20121 等管理体系开展二方/三方审核、供应商审核、符合性审核、审核发现和改进跟踪。",
    "services.research.title": "科研、白皮书与标准知识产品",
    "services.research.copy": "依托高校科研合作与行业资料库，形成白皮书、行业指南、模板库、培训教材、论文合作和标准化技术文件，服务长期知识订阅和专业培训。",
    "services.training.title": "企业培训与国际研学",
    "services.training.copy": "ISO 14064/14067、NEA CPA、CBAM、SGX/ISSB披露、IASE ESG、ISO 14001:2026、IWA 42/48、半导体高GWP气体和可核查MRV课程。",
    "pricing.kicker": "Engagement Boundary",
    "pricing.title": "先确认角色边界、独立性和工作范围",
    "pricing.copy": "正式接项前，Enerstay 会先确认项目是否属于培训、资料审阅、二方审核、三方审核、GHG verification / validation、独立复核或科研合作，并完成利益冲突与独立性判断。",
    "pricing.step1.label": "免费",
    "pricing.step1.title": "初步沟通与角色判断",
    "pricing.step1.copy": "确认行业、标准、目标用途、是否涉及正式保证/核查结论，以及 Enerstay 是否适合承担该角色。",
    "pricing.step2.label": "边界",
    "pricing.step2.title": "明确边界、证据和交付物",
    "pricing.step2.copy": "明确组织/产品/项目边界、标准依据、证据要求、抽样逻辑、交付物和不承担事项。",
    "pricing.step3.label": "独立性",
    "pricing.step3.title": "设置独立性和利益冲突控制",
    "pricing.step3.copy": "对可能进入二方/三方审核、GHG verification、validation 或 assurance 的项目，先确认团队角色隔离、技术复核和结论边界。",
    "pricing.cta": "预约边界沟通",
    "categories.kicker": "学术与项目方向",
    "categories.title": "工业碳保证与知识产品方向",
    "categories.lca.title": "生命周期评价与低碳设计",
    "categories.lca.copy": "围绕 ISO 14067、ISO 14040/14044、EPD/产品数据和供应链资料，建立可审阅、可追溯、可复用的产品碳数据包。",
    "categories.ai.title": "数字化 MRV 与复核轨迹",
    "categories.ai.copy": "围绕 evidence management、evidence trail、supplier portal 和 carbon data platform 建立可追溯的数据流和复核记录。",
    "categories.mrv.title": "MRV 与核查方法体系",
    "categories.mrv.copy": "排放边界、活动数据、证据链、复核台账、重要性判断、抽样逻辑和 verification-ready documentation。",
    "categories.esg.title": "企业 ESG 与气候能力训练",
    "categories.esg.copy": "可持续报告中的环境数据控制、Scope 3、供应商数据保证、上市公司披露证据审阅和内部证据管理培训。",
    "categories.industry.title": "先进制造与半导体减排",
    "categories.industry.copy": "半导体、化工、制造、物流、金属、航空与新能源供应链中的高 GWP 气体、工艺排放、能源记录和复杂边界判断。",
    "categories.translation.title": "高校科研与标准知识转化",
    "categories.translation.copy": "与高校、实验室和行业伙伴形成白皮书、论文、课程、模板、数据库和标准/指南项目，支撑长期知识产品。",
    "standards.kicker": "标准与框架",
    "standards.title": "核查、验证、保证与培训覆盖的标准框架",
    "standards.copy": "下列标识用于说明 Enerstay 工作中可能采用或参考的标准、框架和市场规则。正式 verification、validation、assurance 或二方/三方审核仅在相应授权范围、独立性要求、客户委托、保密协议和适用认可规则内开展。",
    "standards.iso14064": "ISO 14064-1 组织层面 GHG、ISO 14064-2 项目减排量、ISO 14064-3 validation / verification 要求。",
    "standards.iso14067": "产品碳足迹量化、报告、数据质量、边界、分配规则、critical review 和 verification-ready evidence。",
    "standards.iso14068": "碳中和声明、减排优先、抵消使用、声明管理、证据边界和保证证据审阅。",
    "standards.lca": "生命周期评价方法、功能单位、清单分析、影响评价与解释。",
    "standards.pas2080": "建筑与基础设施全生命周期碳管理、低碳设计与价值链协同。",
    "standards.systems": "能源、环境、职业健康安全管理体系二方/三方审核、供应商审核和审核发现跟踪。",
    "standards.disclosure": "气候风险、碳目标、披露问卷、企业减排目标与数据治理。",
    "standards.assurance": "ISSB/SGX 可持续披露、报告保证、重要性议题、利益相关方回应与证据准备。",
    "standards.iwa": "净零指南、气候行动实施框架、组织减排路径和供应链协同训练。",
    "method.kicker": "Delivery Controls",
    "method.title": "从委托边界到证据结论的交付控制",
    "method.copy": "Enerstay 将标准条款、技术判断、证据链、质量复核和独立性控制放在同一流程里，确保二方/三方审核、GHG verification / validation、培训和科研合作之间边界清晰。",
    "method.one.title": "角色与范围确认",
    "method.one.copy": "确认项目性质、适用标准、组织/产品/项目边界、利益冲突和是否能承担独立角色。",
    "method.two.title": "证据与数据控制",
    "method.two.copy": "建立证据索引、活动数据、排放因子、监测计划、供应商资料、复核记录和版本控制。",
    "method.three.title": "核查/审核执行",
    "method.three.copy": "按二方/三方审核、verification、validation 或技术复核程序执行抽样、访谈、记录审阅和发现管理。",
    "method.four.title": "技术复核与结论边界",
    "method.four.copy": "对关键判断、发现关闭、技术复核、声明边界和对外表达进行质量控制。",
    "training.kicker": "培训课程",
    "training.title": "培训课程与能力训练",
    "training.copy": "Enerstay Sustainability Academy 基于自有教材、案例练习、数据表、报告模板与考核材料，为企业、高校、园区和协会提供中英双语课程；课程与 Applus+、NEA CPA、香港 IASE、SGX/ISSB、IWA 等路径衔接，但不等同于正式核查或保证结论。",
    "training.system.kicker": "Enerstay Sustainability Academy",
    "training.system.title": "从政策理解、数据治理到核查/保证证据审阅的课程体系",
    "training.system.copy": "课程分为公开课、企业内训、合作证书课程和专项技术训练四层，可按行业、监管压力、岗位角色和能力目标组合。官网不公开列示具体费用，正式方案以课程人数、语言、场地、考核和课程材料边界确认。",
    "training.lead.training": "培训课程主管",
    "training.lead.audit": "审核项目主管",
    "training.applus.title": "Applus+ CBAM Training 系列",
    "training.applus.copy": "面向欧盟出口链条、钢铝及下游制造供应链，设置管理决策、数据填报、QA/QC 质控三条路径，训练 CBAM 范围判断、嵌入排放、监测计划、证据链、MQCP 和核查问询应对。",
    "training.applus.item1": "管理层：责任矩阵、扩围影响判断、年度证据审阅路线。",
    "training.applus.item2": "数据团队：产品线、活动数据、排放因子和申报资料包。",
    "training.applus.item3": "质控团队：内部审阅、证据缺口识别和模拟核查问题表。",
    "training.nea.title": "NEA CPA 碳定价法案特色课程",
    "training.nea.copy": "针对新加坡 Carbon Pricing Act 下的可报告设施、排放报告、核查证据审阅和管理层责任，结合复杂行业与半导体数据链经验，训练企业把碳税合规做成可审核的内部流程。",
    "training.nea.item1": "边界识别、排放源分类、活动数据和证据留存。",
    "training.nea.item2": "监测计划、内部 QA/QC、第三方核查前资料审阅。",
    "training.nea.item3": "复杂行业数据口径、异常处理和管理层汇报。",
    "training.iase.title": "香港 IASE 授权 ESG Level 1 & 2",
    "training.iase.copy": "面向 ESG 基础能力、可持续金融和进阶实务能力训练，覆盖 ESG 原则、风险治理、可持续投资、报告框架、利益相关方沟通和案例测评，可中英双语授课。",
    "training.iase.item1": "Level 1：ESG 基础、术语、市场趋势和基础测评。",
    "training.iase.item2": "Level 2：实务方法、披露实践、案例分析和应用演练。",
    "training.iase.item3": "适合企业 ESG 团队、金融机构、高校和专业团队。",
    "training.sgx.title": "SGX Sustainability Report 两天课程",
    "training.sgx.copy": "围绕 ISSB 要求和新加坡上市公司可持续报告实践，训练治理、战略、风险管理、指标与目标、气候相关披露、数据控制和内部审阅流程。",
    "training.sgx.item1": "第 1 天：ISSB/SGX 框架、重要性议题和披露结构。",
    "training.sgx.item2": "第 2 天：数据表、证据链、董事会汇报和报告审阅。",
    "training.sgx.item3": "可配套企业现有报告差距分析与整改清单。",
    "training.pathway1.title": "标准与核查课程",
    "training.pathway1.copy": "ISO 14064、ISO 14067、ISO 14068、ISO 14001、IWA 42、IWA 48、PAS 2060、PAS 2080 与内部审核训练。",
    "training.pathway2.title": "披露、ESG 与供应链课程",
    "training.pathway2.copy": "ISSB/SGX 披露、IASE ESG、CBAM、供应链碳数据、可持续报告、保证证据审阅和供应商资料包。",
    "training.pathway3.title": "行业与项目实战课程",
    "training.pathway3.copy": "NEA CPA、半导体减排、先进制造、能源效率、REG(E) 项目逻辑、MRV 证据包和管理层汇报。",
    "training.iso.title": "ISO 14064 GHG Verification / Validation",
    "training.iso.copy": "覆盖 ISO 14064-1、14064-2、14064-3 的组织边界、项目减排、validation / verification 流程、抽样、重要性、证据链与发现管理。",
    "training.pcf.title": "ISO14067 产品碳足迹与 LCA",
    "training.pcf.copy": "围绕产品边界、功能单位、活动数据、排放因子、分配规则、报告结构、critical review 和 verification-ready evidence 开展工作坊。",
    "training.netzero.title": "净零排放路径与碳中和报告",
    "training.netzero.copy": "结合 ISO 14068、PAS 2060、IWA 42、碳中和和净零差异，训练声明边界、减排优先、抵消使用和保证证据审阅。",
    "training.semiconductor.title": "半导体与先进制造减排",
    "training.semiconductor.copy": "聚焦 PFC、NF3、N2O 等高 GWP 气体，尾气处理设备、工艺排放、设备记录、碳税合规和 MRV 证据链。",
    "training.esg.title": "ESG 环境数据与披露保证训练",
    "training.esg.copy": "从 ISSB/SGX 环境指标、Scope 3、数据控制、报告框架到保证证据审阅，训练企业形成可复核的披露证据。",
    "training.wsh.title": "环境安全与职业健康课程",
    "training.wsh.copy": "可覆盖 ISO45001、工作场所安全、受限空间作业、应急响应、HAZMAT 与安全管理体系。",
    "training.toolkit.title": "Enerstay 碳数据与报告工具包",
    "training.toolkit.copy": "使用 Enerstay 自有教材、计算表、访谈清单和报告模板，训练团队完成数据收集、边界判断、证据整理和管理层汇报。",
    "training.iwa42.title": "IWA 42 净零指南训练",
    "training.iwa42.copy": "围绕净零原则、组织边界、减排优先、抵消使用、声明管理和路线图治理开展实践型课程。",
    "training.iwa48.title": "IWA 48 气候行动实施课程",
    "training.iwa48.copy": "把组织气候行动、适应与减缓、指标管理、供应链协同和实施路线连接到企业管理流程。",
    "training.iso14001.title": "ISO14001:2026 转版与内审训练",
    "training.iso14001.copy": "针对环境管理体系转版、合规义务、生命周期思维、风险机会、内审计划和整改闭环开展专项训练。",
    "training.cpa.title": "NEA CPA 碳定价法案培训",
    "training.cpa.copy": "围绕新加坡碳税、可报告设施、排放报告、核查证据审阅、复杂行业数据链和管理层责任开展实务课程。",
    "cases.kicker": "项目经验",
    "cases.title": "工业项目经验与匿名化案例",
    "cases.copy": "团队经验覆盖全球头部半导体公司、新加坡大型工业设施、先进制造供应链、行业协会和高校科研平台。以下内容仅按能力和场景描述，客户名称、底稿、项目结论和商业细节均不公开披露。",
    "cases.chip1": "半导体",
    "cases.chip2": "航空制造",
    "cases.chip3": "金属冶炼",
    "cases.chip4": "新能源电池",
    "cases.chip5": "建筑环境",
    "cases.chip6": "废弃物管理",
    "cases.metricYear": "2020至今",
    "cases.metric1": "ISO 14064、碳税与工业MRV经验",
    "cases.metric2": "Applus+等企业合作与培训路径",
    "cases.metric3": "大型半导体与复杂工业场景",
    "cases.edb.title": "全球头部半导体与复杂工业 MRV",
    "cases.edb.copy": "围绕高 GWP 气体、尾气处理设备、活动数据、设备运行记录、排放因子、异常数据和证据链开展核查证据审阅、技术复核和工业 MRV 资料管理。",
    "cases.nea.title": "新加坡碳税与 NEA CPA evidence review",
    "cases.nea.copy": "围绕可报告设施碳定价法案要求、排放报告、verification evidence review、复杂行业数据链、内部 QA/QC、管理层责任和独立复核资料审阅。",
    "cases.sra.title": "中国矿业大学碳中和研究平台与科研合作",
    "cases.sra.copy": "科研合作方向参考中国矿业大学碳中和研究院等高校平台，聚焦 CCUS、高效碳捕集、二氧化碳利用与封存、碳监测、论文训练、白皮书和标准化知识产品。",
    "research.kicker": "科研与教育",
    "research.title": "以高校实验室、行业伙伴和知识产品支撑科研转化",
    "research.copy": "Enerstay Sustainability Academy 将高校实验室资源、行业伙伴经验和工业碳保证主题转化为白皮书、技术指南、课程教材、论文合作、标准/指南项目和模板数据库。科研合作参考中国矿业大学碳中和研究院等平台公开方向。",
    "research.item1": "以工业碳保证、CCUS、碳捕集与封存、碳监测、Scope 3、CBAM、半导体高GWP气体和AI-MRV为主线组织课程和课题。",
    "research.item2": "形成“技术问题识别、证据链设计、数据治理、模型分析、论文写作、同行评审回应”的科研训练链条。",
    "research.item3": "支持 SCI、SSCI、ESCI、EI 等论文合作、白皮书、行业指南、模板库、培训教材和标准化文件。",
    "research.scholar": "Google Scholar",
    "research.cumt": "中国矿业大学碳中和平台",
    "credentials.kicker": "Licenses & Certifications",
    "credentials.title": "重点专业资质与监管授权",
    "credentials.copy": "这里只展示与保证、核查、验证、二方/三方审核、培训和科研合作直接相关的核心资质，不列出证书号码和授权截止日期。完整证明材料可在项目尽调或合作流程中提供。",
    "credentials.edb.title": "Independent Qualified Endorser for REG(E)",
    "credentials.edb.copy": "可围绕资源效率与减排项目开展技术评估、节能量与排放减量逻辑审阅、MRV 证据包和第三方背书资料审阅。",
    "credentials.edb.meaning": "客户意义：支持 REG(E) 等资源效率项目所需的技术背书、证据组织和独立评估材料。",
    "credentials.nea.title": "Accredited Lead Verifier / Independent Reviewer / Semiconductor Complex Sector Expert",
    "credentials.nea.copy": "聚焦新加坡碳定价法案下的排放核查、独立复核和半导体复杂行业技术判断，支持高风险数据与边界问题处理。",
    "credentials.nea.meaning": "客户意义：可把碳税合规、复杂排放源和核查证据链提前做成可核查状态。",
    "credentials.sra.title": "Academic, Applus+ & Standards Collaboration",
    "credentials.sra.copy": "连接中国矿业大学碳中和研究平台、Applus+ 等企业合作资源、ISO/PAS/ISSB/IWA 标准训练和科研/白皮书/模板库输出。",
    "credentials.sra.meaning": "客户意义：将产业数据、标准要求和科研成果转化为培训、白皮书、模板、课程和长期知识产品。",
    "credentials.cat1": "碳、净零与保证",
    "credentials.cat2": "法规、管理体系与 ESG",
    "credentials.cat3": "安全、韧性与专业训练",
    "contact.kicker": "Contact",
    "contact.title": "确认审核、核查、培训或科研合作的下一步",
    "contact.copy": "欢迎说明行业、地区、标准、目标用途和时间线。Enerstay 会先判断角色边界、独立性要求和适用路径，再进入二方/三方审核、GHG verification / validation、培训或科研合作安排。",
    "contact.whatsappLabel": "WhatsApp",
    "contact.phoneLabel": "电话",
    "contact.emailLabel": "邮箱",
    "contact.addressLabel": "地址",
    "form.name": "姓名 / Name",
    "form.email": "邮箱 / Email",
    "form.need": "需求 / Requirement",
    "form.placeholder": "请选择需求类型",
    "form.option1": "GHG verification / validation",
    "form.option2": "ISO 二方/三方审核",
    "form.option3": "NEA CPA / 工业MRV",
    "form.option4": "科研/白皮书/知识产品",
    "form.option5": "企业培训",
    "form.message": "项目背景 / Message",
    "form.submit": "发送联系",
    "footer.copy": "Enerstay Sustainability Pte. Ltd. | 新加坡工业碳保证、GHG核查/验证、二方/三方审核、培训与科研知识平台。"
  },
  en: {
    "nav.services": "Services",
    "nav.categories": "Tracks",
    "nav.standards": "Standards",
    "nav.training": "Training",
    "nav.cases": "Experience",
    "nav.contact": "Contact",
    "hero.eyebrow": "Industrial Carbon Assurance · GHG Verification / Validation · Second/Third-Party Audits · Research",
    "hero.title": "Industrial carbon assurance and standards platform",
    "hero.copy": "Enerstay Sustainability focuses on industrial carbon assurance, GHG verification / validation, ISO management-system second/third-party audits, executive training, digital MRV and research-based knowledge products. Assurance, verification and audit roles are separated from preparation and training work.",
    "hero.calendly": "Book a discussion",
    "hero.cta": "Book a discussion",
    "hero.secondary": "Explore capabilities",
    "stats.years": "Years of industrial project continuity",
    "stats.papers": "SCI/SSCI publications and collaboration outputs",
    "stats.standards": "Carbon, ESG, energy and safety standards",
    "intro.kicker": "About Enerstay",
    "intro.title": "Connecting industrial carbon assurance, standards audits and research products",
    "intro.copy": "Enerstay Sustainability Pte. Ltd. is registered in Singapore and positioned as an industrial carbon assurance and professional standards platform, focusing on NEA CPA evidence review, ISO 14064 / 14067, complex-sector high-GWP gases, CBAM data, ESG environmental data controls, second/third-party audits, executive training, digital MRV, publications and standardisation knowledge products.",
    "founder.kicker": "Who Leads The Work",
    "founder.title": "Led by Dr. Strange",
    "founder.copy": "Enerstay Sustainability is led by Dr. Strange, connecting Singapore carbon regulation, GHG verification / validation, ISO management-system audits, semiconductor high-GWP gases and research training. Assurance, verification and audit work is controlled by independence, conflict-of-interest and authorization boundaries.",
    "founder.point1": "NEA carbon-pricing verification and complex-sector experience",
    "founder.point2": "Applus+ collaboration and CBAM training resources",
    "founder.point3": "SCI, SSCI, ESCI and EI publication collaboration and research training",
    "founder.linkedin": "LinkedIn",
    "founder.scholar": "Google Scholar",
    "images.energy": "Semiconductor cleanroom and abatement engineering",
    "images.research": "Research training and project defense",
    "images.training": "Low-carbon energy and implementation",
    "services.kicker": "Assurance, Training & Knowledge",
    "services.title": "Industrial carbon assurance, second/third-party audits and knowledge products",
    "services.carbon.title": "GHG Verification, Validation & Assurance Evidence Review",
    "services.carbon.copy": "Second- or third-party work around ISO 14064-1, ISO 14064-2, ISO 14064-3, ISO 14065 and ISO 14066, covering organizational GHG, project reductions, validation / verification procedures, evidence sampling, materiality and conclusion boundaries.",
    "services.esg.title": "ESG Environmental Data Controls & Assurance Evidence Review",
    "services.esg.copy": "Focused on environmental data, Scope 3, supplier data packs, evidence chains, internal controls and assurance evidence review for ISSB / SGX disclosure; formal audit or assurance conclusions are separated from training and research activities.",
    "services.energy.title": "Industrial MRV & Digital Evidence Trails",
    "services.energy.copy": "Review verification-ready MRV structures covering activity data, emission factors, equipment records, supplier evidence, evidence trails, exception handling and digital evidence packs.",
    "services.material.title": "ISO Second/Third-Party Management-System Audits",
    "services.material.copy": "Second/third-party audits, supplier audits, conformity audits, findings and follow-up for ISO 14001, ISO 45001, ISO 50001, Responsible Care 14001 and ISO 20121 management systems.",
    "services.research.title": "Research, White Papers & Standards Knowledge Products",
    "services.research.copy": "Transform university and industry collaboration into white papers, industry guides, template libraries, training materials, publication collaboration and standards-oriented technical documents.",
    "services.training.title": "Corporate Training & International Programs",
    "services.training.copy": "Courses cover ISO 14064/14067, NEA CPA, CBAM, SGX/ISSB disclosure, IASE ESG, ISO 14001:2026, IWA 42/48, semiconductor high-GWP gases and verification-ready MRV.",
    "pricing.kicker": "How To Start",
    "pricing.title": "Start with role boundaries, independence and scope",
    "pricing.copy": "Before taking on work, Enerstay clarifies whether the request is training, evidence review, second-party audit, third-party audit, GHG verification / validation, independent review or research collaboration, and checks independence and conflicts of interest.",
    "pricing.step1.label": "Free",
    "pricing.step1.title": "Role and fit check",
    "pricing.step1.copy": "Confirm sector, standard, intended use, whether a formal assurance or verification conclusion is involved, and whether Enerstay can take the role.",
    "pricing.step2.label": "Scoping",
    "pricing.step2.title": "Define boundaries, evidence and deliverables",
    "pricing.step2.copy": "Define organizational, product or project boundaries, applicable standards, evidence requirements, sampling logic, deliverables and exclusions.",
    "pricing.step3.label": "Custom quote",
    "pricing.step3.title": "Set independence and conflict controls",
    "pricing.step3.copy": "For second/third-party audits, GHG verification, validation or assurance-related work, confirm role separation, technical review and conclusion boundaries before engagement.",
    "pricing.cta": "Book a boundary discussion",
    "categories.kicker": "Academic & Project Tracks",
    "categories.title": "Academic and project focus areas",
    "categories.lca.title": "Life Cycle Assessment & Low-Carbon Design",
    "categories.lca.copy": "LCA / PCF research and enterprise application for buildings, infrastructure, mining and materials, including cradle-to-gate and cradle-to-grave boundaries.",
    "categories.ai.title": "AI Building Energy & Carbon Baselines",
    "categories.ai.copy": "Energy baselines, anomaly detection, benchmarking, savings quantification and data models connected to MRV and compliance reporting.",
    "categories.mrv.title": "MRV & Verification Methodology",
    "categories.mrv.copy": "Emission boundaries, activity data, evidence chains, review logs, materiality judgement, sampling logic and verification-ready documentation.",
    "categories.esg.title": "Corporate ESG & Climate Capability",
    "categories.esg.copy": "Sustainability reporting, climate disclosure, green supply chains, listed-company evidence review and internal carbon management training.",
    "categories.industry.title": "Advanced Manufacturing & Semiconductor Abatement",
    "categories.industry.copy": "Reduction pathways and engineering plans for semiconductor, aerospace, metal, chemical, battery and waste-management sectors.",
    "categories.translation.title": "Research Commercialization & Translation",
    "categories.translation.copy": "University and industry collaboration that turns evidence packages, PCF/LCA methods, research findings and standards knowledge into reusable papers, templates and training materials.",
    "standards.kicker": "Standards & Frameworks",
    "standards.title": "Standards for verification, validation, assurance and training",
    "standards.copy": "These marks identify standards, frameworks and market protocols referenced by Enerstay work. Formal verification, validation, assurance and second/third-party audit engagements are performed only within the relevant authorization scope, independence requirements, client mandate, NDAs and applicable accreditation rules.",
    "standards.iso14064": "ISO 14064-1 organizational GHG, ISO 14064-2 project reductions and ISO 14064-3 validation / verification requirements.",
    "standards.iso14067": "Product carbon footprint quantification, reporting, data quality, boundaries, allocation, critical review and verification-ready evidence.",
    "standards.iso14068": "Carbon neutrality claims, net-zero pathways, reduction-first principles and residual-emission treatment.",
    "standards.lca": "LCA methodology, functional units, inventory analysis, impact assessment and interpretation.",
    "standards.pas2080": "Whole-life carbon management for buildings and infrastructure, low-carbon design and value-chain collaboration.",
    "standards.systems": "Second/third-party audits, supplier audits and findings follow-up for energy, environmental and occupational health and safety management systems.",
    "standards.disclosure": "Climate risk, carbon targets, disclosure questionnaires, corporate reduction goals and data governance.",
    "standards.assurance": "ISSB/SGX sustainability disclosure, report assurance, materiality topics, stakeholder response and evidence preparation.",
    "standards.iwa": "Net-zero guidance, climate-action implementation, organizational reduction pathways and supply-chain collaboration training.",
    "method.kicker": "How We Work",
    "method.title": "Delivery controls from engagement boundary to evidence conclusion",
    "method.copy": "Enerstay combines standard clauses, technical judgement, evidence chains, quality review and independence controls so that second/third-party audits, GHG verification / validation, training and research collaboration remain clearly separated.",
    "method.one.title": "Diagnosis",
    "method.one.copy": "Define emission boundaries, data sources, energy structure and compliance gaps.",
    "method.two.title": "Evidence Control",
    "method.two.copy": "Set up carbon and energy governance structures, SOPs, monitoring plans and internal review rules.",
    "method.three.title": "Implementation",
    "method.three.copy": "Design decarbonization projects and evaluate savings, emission reductions and government support routes.",
    "method.four.title": "Verification",
    "method.four.copy": "Support third-party certification, report review, outcome retention and the next optimization cycle.",
    "training.kicker": "Training Programs",
    "training.title": "Training programs and capability training",
    "training.copy": "Enerstay Sustainability Academy can customize bilingual programs for companies, universities, industrial parks and research teams using Enerstay's own materials, case exercises, data sheets, report templates and assessment packs. Programs can also connect with Applus+, NEA CPA and Hong Kong IASE partner courses across public classes, in-house training, joint certificates and specialist coaching.",
    "training.system.kicker": "Enerstay Sustainability Academy",
    "training.system.title": "A training system from policy literacy and data governance to verification evidence review",
    "training.system.copy": "Programs are organized into public courses, in-house training, partner certificate courses and specialist technical training. They can be combined by sector, regulatory pressure, job role and capability objective. Detailed fees are not listed publicly; formal proposals are scoped by cohort size, language, venue, assessment and course-material boundary.",
    "training.lead.training": "Training Program Lead",
    "training.lead.audit": "Audit Project Lead",
    "training.applus.title": "Applus+ CBAM Training Series",
    "training.applus.copy": "For EU export chains, steel/aluminium and downstream manufacturing suppliers, the series offers management, data reporting and QA/QC tracks covering CBAM scope checks, embedded emissions, monitoring plans, evidence chains, MQCP and verification-question handling.",
    "training.applus.item1": "Management: responsibility matrix, expansion-impact assessment and annual evidence-review roadmap.",
    "training.applus.item2": "Data teams: product lines, activity data, emission factors and declaration packs.",
    "training.applus.item3": "QA/QC teams: internal review, evidence-gap checks and simulated verification questions.",
    "training.nea.title": "NEA CPA Carbon Pricing Act Specialist Course",
    "training.nea.copy": "For reportable facilities, emissions reporting, verification evidence review and management accountability under Singapore's Carbon Pricing Act, this course uses complex-sector and semiconductor data-chain experience to turn carbon-tax compliance into an auditable internal process.",
    "training.nea.item1": "Boundary identification, emission-source classification, activity data and evidence retention.",
    "training.nea.item2": "Monitoring plans, internal QA/QC and pre-verification documentation.",
    "training.nea.item3": "Complex-sector data positions, exception handling and management reporting.",
    "training.iase.title": "Hong Kong IASE Authorized ESG Level 1 & 2",
    "training.iase.copy": "For ESG foundations, sustainable finance and advanced practitioner capability, covering ESG principles, risk governance, sustainable investment, reporting frameworks, stakeholder communication and case assessment in bilingual delivery.",
    "training.iase.item1": "Level 1: ESG foundations, terminology, market trends and baseline assessment.",
    "training.iase.item2": "Level 2: practitioner methods, disclosure practice, case analysis and applied exercises.",
    "training.iase.item3": "Suitable for corporate ESG teams, financial institutions, universities and professional teams.",
    "training.sgx.title": "Two-Day SGX Sustainability Report Course",
    "training.sgx.copy": "Built around ISSB requirements and SGX sustainability-reporting practice, covering governance, strategy, risk management, metrics and targets, climate disclosure, data controls and internal review workflows.",
    "training.sgx.item1": "Day 1: ISSB/SGX framework, material topics and disclosure structure.",
    "training.sgx.item2": "Day 2: data sheets, evidence chains, board reporting and report review.",
    "training.sgx.item3": "Can include a gap assessment and corrective-action list for existing reports.",
    "training.pathway1.title": "Standards and Verification Courses",
    "training.pathway1.copy": "ISO 14064, ISO 14067, ISO 14068, ISO 14001, IWA 42, IWA 48, PAS 2060, PAS 2080 and internal audit training.",
    "training.pathway2.title": "Disclosure, ESG and Supply-Chain Courses",
    "training.pathway2.copy": "ISSB/SGX disclosure, IASE ESG, CBAM, supply-chain carbon data, sustainability reports, assurance evidence review and supplier data packs.",
    "training.pathway3.title": "Industry and Project Practice Courses",
    "training.pathway3.copy": "NEA CPA, semiconductor abatement, advanced manufacturing, energy efficiency, REG(E) project logic, MRV evidence packs and management reporting.",
    "training.iso.title": "ISO 14064 GHG Verification / Validation",
    "training.iso.copy": "Covers ISO 14064-1, 14064-2 and 14064-3, including organizational boundaries, project reductions, validation / verification flow, sampling, materiality, evidence chains and findings management.",
    "training.pcf.title": "ISO14067 Product Carbon Footprint & LCA",
    "training.pcf.copy": "Workshops on product boundaries, functional units, activity data, emission factors, allocation rules, report structure and certification evidence review.",
    "training.netzero.title": "Net-Zero Pathways & Carbon Neutrality Reports",
    "training.netzero.copy": "Connects ISO14068, PAS2060, carbon peak, carbon neutrality and net zero into an enterprise roadmap and management plan.",
    "training.semiconductor.title": "Semiconductor & Advanced Manufacturing Abatement",
    "training.semiconductor.copy": "Industry training based on semiconductor exhaust treatment, energy systems, process abatement and carbon-tax compliance experience.",
    "training.esg.title": "ESG Environmental Data & Assurance Evidence Review Training",
    "training.esg.copy": "From topic identification, metrics and data governance to reporting frameworks and assurance preparation.",
    "training.wsh.title": "Environmental Safety & Occupational Health Courses",
    "training.wsh.copy": "Can cover ISO45001, workplace safety, confined-space operations, emergency response, HAZMAT and safety management systems.",
    "training.toolkit.title": "Enerstay Carbon Data & Reporting Toolkit",
    "training.toolkit.copy": "Uses Enerstay's own manuals, calculators, interview checklists and report templates to train teams on data collection, boundary decisions, evidence control and management reporting.",
    "training.iwa42.title": "IWA 42 Net-Zero Guideline Training",
    "training.iwa42.copy": "Practical training on net-zero principles, organizational boundaries, reduction-first logic, offset use, claims management and roadmap governance.",
    "training.iwa48.title": "IWA 48 Climate Action Implementation Course",
    "training.iwa48.copy": "Connects organizational climate action, adaptation and mitigation, metrics management, supply-chain collaboration and implementation roadmaps to enterprise management processes.",
    "training.iso14001.title": "ISO14001:2026 Transition & Internal Audit Training",
    "training.iso14001.copy": "Specialist training on EMS transition, compliance obligations, life-cycle thinking, risks and opportunities, internal audit planning and corrective-action closure.",
    "training.cpa.title": "NEA CPA Carbon Pricing Act Training",
    "training.cpa.copy": "Practical courses on Singapore carbon tax, reportable facilities, emissions reporting, verification evidence review, complex-sector data chains and management accountability.",
    "cases.kicker": "Experience",
    "cases.title": "Industrial experience and anonymized cases",
    "cases.copy": "Experience covers global leading semiconductor companies, major Singapore industrial facilities, advanced manufacturing supply chains, industry associations and university research platforms. The content below is described by capability and scenario only; client names, working papers, conclusions and commercial details remain confidential.",
    "cases.chip1": "Semiconductor",
    "cases.chip2": "Aerospace",
    "cases.chip3": "Metal Smelting",
    "cases.chip4": "New Energy Batteries",
    "cases.chip5": "Built Environment",
    "cases.chip6": "Waste Management",
    "cases.metricYear": "2020-present",
    "cases.metric1": "ISO 14064, carbon-tax and industrial MRV experience",
    "cases.metric2": "Applus+ and enterprise collaboration pathways",
    "cases.metric3": "Large semiconductor and complex-sector scenarios",
    "cases.edb.title": "Global leading semiconductor and complex-sector MRV",
    "cases.edb.copy": "Work involves high-GWP gases, abatement equipment, activity data, equipment operation records, emission factors, abnormal data handling and evidence-chain control for verification evidence review and industrial MRV.",
    "cases.nea.title": "Singapore carbon tax and NEA CPA evidence review",
    "cases.nea.copy": "Experience covers emissions reporting under Singapore's carbon-pricing framework, verification evidence review, complex-sector data review and semiconductor emission-source management, improving data quality and audit traceability.",
    "cases.sra.title": "CUMT carbon-neutrality research platform and academic collaboration",
    "cases.sra.copy": "Academic collaboration references public research directions from the China University of Mining and Technology carbon-neutrality platform, including CCUS, efficient carbon capture, CO2 utilization and storage, carbon monitoring, papers, white papers and standards knowledge products.",
    "research.kicker": "Research & Education",
    "research.title": "Research translation backed by university laboratories, industry partners and knowledge products",
    "research.copy": "Enerstay Sustainability Academy converts university laboratory resources, industry partner experience and industrial carbon assurance topics into white papers, technical guides, training materials, publication collaboration, standards/guideline projects and template databases. Academic collaboration references public directions from platforms such as the CUMT Carbon Neutrality Institute.",
    "research.item1": "Organize courses and research topics around industrial carbon assurance, CCUS, carbon capture and storage, carbon monitoring, Scope 3, CBAM, semiconductor high-GWP gases and AI-MRV.",
    "research.item2": "Operate a research-training chain from topic design, data governance and modeling to paper writing and reviewer response.",
    "research.item3": "Support SCI, SSCI, ESCI, EI and related publication collaboration, research project management and application translation.",
    "research.scholar": "Google Scholar",
    "research.cumt": "CUMT carbon-neutrality platform",
    "credentials.kicker": "Licenses & Certifications",
    "credentials.title": "Key professional qualifications and regulatory authorizations",
    "credentials.copy": "This section highlights qualifications related to assurance, verification, validation, second/third-party audits, training and academic collaboration. Certificate numbers and authorization expiry dates are not listed publicly; supporting evidence can be provided during due diligence.",
    "credentials.edb.title": "Independent Qualified Endorser for REG(E)",
    "credentials.edb.copy": "Supports technical assessment for resource-efficiency and abatement projects, savings and emissions-reduction logic, government grant submissions and MRV evidence packages.",
    "credentials.edb.meaning": "Client value: supports the technical endorsement and evidence pack required for REG(E) grant applications.",
    "credentials.nea.title": "Accredited Lead Verifier / Independent Reviewer / Semiconductor Complex Sector Expert",
    "credentials.nea.copy": "Focused on emissions verification, independent review and semiconductor complex-sector judgement under Singapore's carbon-pricing framework, especially for high-risk data and boundary issues.",
    "credentials.nea.meaning": "Client value: carbon-tax compliance, complex emission sources and verification evidence can be prepared before verification pressure peaks.",
    "credentials.sra.title": "Academic, Applus+ & Standards Collaboration",
    "credentials.sra.copy": "Connects CUMT carbon-neutrality research resources, Applus+ collaboration, ISO/PAS/ISSB/IWA training and research outputs such as papers, white papers and template libraries.",
    "credentials.sra.meaning": "Client value: one data foundation can support reporting, certification, training and research translation.",
    "credentials.cat1": "Carbon, Net Zero & Assurance",
    "credentials.cat2": "Regulatory, Management Systems & ESG",
    "credentials.cat3": "Safety, Resilience & Professional Training",
    "contact.kicker": "Contact",
    "contact.title": "Clarify the next step for audit, verification, training or research collaboration",
    "contact.copy": "Share your industry, location, applicable standard, intended use and timeline. Enerstay will first check role boundaries, independence and the suitable pathway before arranging second/third-party audit, GHG verification / validation, training or research collaboration.",
    "contact.whatsappLabel": "WhatsApp",
    "contact.phoneLabel": "Phone",
    "contact.emailLabel": "Email",
    "contact.addressLabel": "Address",
    "form.name": "Name",
    "form.email": "Email",
    "form.need": "Requirement",
    "form.placeholder": "Select a requirement",
    "form.option1": "GHG verification / validation",
    "form.option2": "ISO second/third-party audit",
    "form.option3": "NEA CPA / industrial MRV",
    "form.option4": "International research program",
    "form.option5": "Corporate training",
    "form.message": "Project background",
    "form.submit": "Send message",
    "footer.copy": "Enerstay Sustainability Pte. Ltd. | Singapore-based industrial carbon assurance, GHG verification / validation, second/third-party audits, training and research knowledge platform."
  }
};

Object.assign(translations.zh, {
  "nav.home": "首页",
  "nav.credentials": "资质",
  "nav.team": "团队",
  "nav.research": "科研",
  "hero.eyebrow": "半导体 · 工业设施 · 新加坡碳税 · GHG核查/验证",
  "hero.title": "工业碳保证与合规审核",
  "hero.copy": "面向半导体和工业设施开展独立 GHG 核查/验证与 ISO 管理体系二方/三方审核。正式 CPA 项目仅通过适用的 NEA 认可核查机构交付；培训与科研另行管理。",
  "credentials.kicker": "专业资质与范围",
  "hero.meeting": "预约会议",
  "hero.secondary": "查看资质",
  "stats.years": "工业项目经验积累",
  "stats.roles": "核心监管级资质",
  "bridge.copy": "先看资质、角色边界和证据要求，再判断适合的核查、验证、审核、培训或科研路径。",
  "credentials.title": "专业资质与交付边界",
  "credentials.copy": "本页前置展示经筛选的人员资质和项目角色，不构成 Enerstay 获得机构认可的声明。正式核查、验证、保证和二方/三方审核须先确认所需认可机构、授权范围、能力和独立性。",
  "credentials.nea.title": "人员资质：Lead Verifier / Independent Reviewer / Sector 3 Expert",
  "credentials.nea.copy": "适用于通过 NEA 认可核查机构、并在该机构获认可行业范围内交付的碳定价法案核查工作。",
  "credentials.edb.title": "人员资质：REG(E) Independent Qualified Endorser (QE)",
  "credentials.edb.copy": "独立背书仅在满足项目适用资格、委任、能力和利益冲突要求时开展。",
  "credentials.bsi.title": "BSI 颁发的部分人员资质",
  "credentials.bsi.copy": "包括 ISO 14064 GHG 核查、ISO 14068-1 碳中和核查、净零路径核查以及 ISAE 3000 保证培训或资质。",
  "services.energy.copy": "按已约定的核查或审核准则，独立评估活动数据、排放因子、设备记录、供应商信息和复核轨迹。",
  "services.kicker": "Core Capabilities",
  "services.title": "服务能力",
  "services.carbon.copy": "组织 GHG、项目减排、产品碳足迹和披露保证证据审阅，重点是边界、证据、抽样和结论边界。",
  "services.material.title": "管理体系二方/三方审核",
  "services.material.copy": "针对环境、能源、职业健康安全和供应链管理体系开展二方/三方审核、供应商审核和发现跟踪。",
  "services.energy.copy": "按已约定的核查或审核准则，独立评估活动数据、排放因子、设备记录、供应商信息和复核轨迹。",
  "services.cta": "判断适用路径",
  "team.kicker": "Team & Role Separation",
  "team.title": "团队与角色分离",
  "team.copy": "Enerstay 将主理、培训、审核项目协调和外部技术复核分开管理。涉及正式保证、核查、验证或二方/三方审核时，先进行利益冲突和角色边界判断。",
  "team.balance": "负责合规把控、认证治理风险复核、大客户交付和跨境 TIC 协同。背景覆盖 ISO 管理体系认证治理、技术复核和审核员能力体系。",
  "team.yuanzhe": "负责技术方向、复杂行业判断、监管授权边界和关键交付物复核。",
  "team.zeean": "负责企业培训、合作证书课程、学员沟通和 Enerstay Academy 课程交付。",
  "team.jiahui": "负责审核项目排期、文件协调、客户沟通和项目过程质量跟踪。",
  "team.partner.title": "认证机构与 IMS 合作网络",
  "team.partner.copy": "涉及中国市场 IMS 三体系、供应商审核和认证机构资源时，可通过保密合作网络进行技术协同；具体合作方信息按项目保密要求处理。",
  "cases.title": "匿名化案例与项目经验",
  "cases.copy": "客户名称、底稿和项目结论不公开；以下仅保留行业、规模和能力边界，用于说明典型场景。",
  "cases.edb.m1": "排放源/资料类型",
  "cases.edb.m2": "工业项目经验",
  "cases.nea.m1": "碳定价法案路径",
  "cases.nea.m2": "半导体复杂行业",
  "cases.sra.m1": "论文/合作成果",
  "cases.sra.m2": "课程与白皮书",
  "cases.edb.copy": "高 GWP 气体、尾气处理设备、活动数据、设备记录、异常数据和证据链控制。",
  "cases.nea.copy": "排放报告、verification evidence review、复杂数据链、内部 QA/QC、管理层责任和独立复核资料审阅。",
  "cases.sra.title": "高校平台与科研知识产品",
  "cases.sra.copy": "参考中国矿业大学碳中和研究院等高校公开方向，形成课程、论文训练、白皮书和标准化知识产品。",
  "standards.title": "标准与框架",
  "standards.copy": "下方官方标识仅说明经核实的人员资质或项目路径来源。随后的参考矩阵区分业务准则、管理体系审核标准、保证标准、披露参考、碳项目规则和不可认证的指导性文件。",
  "standards.iso14064": "组织 GHG、项目减排、validation / verification",
  "standards.iso14067": "产品碳足迹、LCA、边界、分配和 critical review",
  "standards.iso14068": "碳中和声明、净零路径、减排优先和保证证据审阅",
  "standards.systems": "环境、职业健康安全、能源管理体系审核",
  "standards.assurance": "可持续披露、环境数据控制、报告保证证据审阅",
  "standards.iwa": "欧盟出口链条、净零指南、气候行动实施训练",
  "standards.cta": "确认适用标准",
  "standards.logo.issb": "可持续与气候相关披露要求",
  "standards.logo.tnfd": "自然相关风险与披露框架",
  "standards.logo.sasb": "行业化可持续披露议题",
  "standards.logo.nea": "新加坡碳定价法案报告与核查路径",
  "standards.logo.edb": "资源效率项目证据与背书逻辑",
  "standards.logo.cdp": "气候问卷与披露证据",
  "standards.logo.sbti": "科学碳目标设定参考",
  "standards.logo.ghg": "企业、Scope 2 与 Scope 3 核算参考",
  "standards.logo.verra": "碳项目 validation / verification 参考",
  "standards.logo.aa": "利益相关方、重要性和保证原则",
  "standards.logo.isae3000": "历史财务信息审计或审阅以外的保证业务要求",
  "standards.logo.issa5000": "可持续保证业务通用要求",
  "standards.logo.gold": "气候项目方法学参考",
  "standards.logo.gri": "影响报告与可持续议题参考",
  "standards.logo.isoCarbon": "GHG、PCF 和碳中和核查参考",
  "standards.logo.isoIms": "环境、安全和能源管理体系审核参考",
  "standards.logo.iwa": "净零与气候行动实施指南",
  "standards.boundary.title": "边界说明",
  "standards.boundary.copy": "合同和报告会分别识别业务准则、项目规则和披露参考。本页出现某个名称或标识不代表该机构对 Enerstay 的背书。正式结论仅通过所需的授权或认可路径，并在已确认的能力、独立性和范围内出具。",
  "standards.sources.title": "已核实的资质与项目路径来源",
  "standards.sources.nea": "人员能力仅用于通过 NEA 认可的核查机构、并在其获认可行业范围内交付的工作。",
  "standards.sources.edb": "独立 Qualified Endorser 角色须满足项目委任、适用资格和独立性条件。",
  "standards.sources.bsi": "部分人员核查、审核、净零与保证资质的颁发来源；不代表 Enerstay 获得机构认证。",
  "standards.references.title": "适用准则与参考矩阵",
  "standards.references.copy": "标准名称以文字呈现，因为标准所有方的标识本身并不构成认证、授权或背书的证据。",
  "standards.type.criteria": "业务准则",
  "standards.type.audit": "审核标准",
  "standards.type.assurance": "保证标准",
  "standards.type.disclosure": "披露参考",
  "standards.type.accounting": "核算参考",
  "standards.type.programme": "项目规则",
  "standards.type.guidance": "指南 / 培训",
  "standards.ref.ghg": "组织层面盘查与 GHG validation / verification；适用分部和版本会在业务范围中确认。",
  "standards.ref.pcf": "产品碳足迹与 LCA 原则，包括边界、分配、质量和 critical review 要求。",
  "standards.ref.netzero": "碳中和声明与转型证据。PAS 2060 仅在特定历史或过渡情形需要时保留参考。",
  "standards.ref.ims": "环境、职业健康安全和能源管理体系二方/三方审核，以已约定审核准则为边界。",
  "standards.ref.assurance": "ISAE 3000 用于适用的非财务保证业务；ISSA 5000 在相关司法管辖区采用并生效后用于可持续保证。",
  "standards.ref.disclosure": "仅作为报告与披露参考；使用它们不代表获得框架所有方认证、验证或背书。",
  "standards.ref.protocol": "在报告路径或客户委托要求时作为核算参考；保证准则需另行约定。",
  "standards.ref.programmes": "作为项目方法学和规则使用。正式 validation / verification 仅在项目体系批准的机构与能力范围内开展。",
  "standards.ref.iwa": "用于学习和路径设计的净零与 ESG 实施指南；这些文件不是认证标准。",
  "training.title": "培训课程",
  "training.copy": "Enerstay Sustainability Academy 基于自有教材、案例练习、数据表、报告模板与考核材料，提供企业内训、合作证书课程、审核员能力课程和海外 ESG 研学项目；课程不等同于正式核查或保证结论。",
  "training.group1": "标准核查类",
  "training.group2": "披露与 ESG 类",
  "training.group3": "行业实战与合作课程",
  "training.catalog": "查看完整课程目录",
  "training.corporate": "沟通企业内训",
  "training.meta1.label": "课程时长",
  "training.meta1.value": "1-2 天",
  "training.meta1.copy": "多数 Academy 模块可按强化工作坊交付，也可压缩为管理层简报。",
  "training.meta2.label": "授课形式",
  "training.meta2.value": "线上 / 线下 / 企业班",
  "training.meta2.copy": "支持企业内训、合作证书课程、高校课堂和协会专班。",
  "training.meta3.label": "开课安排",
  "training.meta3.value": "滚动开班",
  "training.meta3.copy": "可按受众、语言、行业和考核要求定制公开班或企业专班。",
  "training.route1.type": "Enerstay 自有",
  "training.route1.title": "Academy 实践课程体系",
  "training.route1.copy": "采用自有课程设计、证据工作表、工业案例和中英双语班级交付。",
  "training.route1.cta": "查看 Academy 课程",
  "training.route2.type": "线上入口",
  "training.route2.title": "APEX 线上学习",
  "training.route2.copy": "直接进入已发布的 ISO 管理体系、审核员能力、合规与质量课程。",
  "training.route2.cta": "打开课程链接",
  "training.route3.type": "合作课程",
  "training.route3.title": "Applus+ 合作专班",
  "training.route3.copy": "选定 CBAM 与技术专班可按项目确认交付、评估与证书角色。",
  "training.route3.cta": "查看合作路径",
  "training.route4.type": "标准来源",
  "training.route4.title": "PAS 与 ISO 转换参考",
  "training.route4.copy": "BSI 仅作为 PAS 2060 发布方和转换信息来源引用，不作为课程合作方呈现。",
  "training.route4.cta": "阅读边界说明",
  "research.title": "科研与知识产品",
  "research.copy": "Enerstay Sustainability Academy 按 ESG 主题与 SDG 目标整理已发表和由 Enerstay 支持的科研成果，并转化为课程案例、白皮书和实践笔记。",
  "research.sdg1.title": "建筑环境、LCA 与可核证减碳",
  "research.sdg1.copy": "AI 建筑能耗基线、全生命周期碳治理和气候韧性建筑路径。",
  "research.sdg1.paper": "2026 · Scientific Reports · AI-enabled energy baselines for verified building decarbonization",
  "research.sdg2.title": "工业排放、Scope 3 与半导体气体",
  "research.sdg2.copy": "半导体高 GWP 气体减排、汽车 Scope 3 数据体系和环境披露分析。",
  "research.sdg2.paper": "2023 · Processes · 新加坡半导体行业 GHG 减排最佳实践",
  "research.sdg3.title": "教育、数据智能与治理",
  "research.sdg3.copy": "AI 教学评价、信贷需求分析和面向 ESG 知识产品的数据素养训练。",
  "research.sdg3.paper": "2026 · Scientific Reports · Intelligent evaluation and feedback mechanism",
  "research.sdg4.title": "应用可持续与现场系统",
  "research.sdg4.copy": "节水栽培、海洋 ROV 系统和资源密集行业的技术路径。",
  "research.sdg4.paper": "2025 · Notulae Botanicae / Scientific Reports · 现场系统与资源效率",
  "research.scholarCard": "70+ 论文与合作成果",
  "research.scholarCardMeta": "Google Scholar 按最新发表排序",
  "research.catalog": "查看科研目录",
  "research.cumt": "中国矿业大学研究方向",
  "research.linkedin": "Enerstay LinkedIn",
  "research.visual.caption": "以证据为基础的科研与知识转化",
  "contact.title": "联系与预约",
  "contact.copy": "建议先通过邮件或预约会议说明行业、地区、标准、目标用途和时间线。Enerstay 会先判断角色边界、独立性要求和适用路径。",
  "contact.meeting": "预约会议",
  "contact.emailCta": "邮件联系",
  "form.option1": "GHG 核查/验证",
  "form.option2": "ISO 审核",
  "form.option3": "NEA CPA / MRV",
  "form.option4": "科研项目",
  "form.option5": "培训",
  "form.submit": "发送邮件"
});

Object.assign(translations.en, {
  "nav.home": "Home",
  "nav.credentials": "Credentials",
  "nav.team": "Team",
  "nav.research": "Research",
  "hero.eyebrow": "Semiconductors · Industrial Facilities · Singapore Carbon Tax · GHG Verification",
  "hero.title": "Industrial carbon assurance and compliance audits",
  "hero.copy": "Independent GHG verification / validation and ISO second/third-party audits for semiconductor and industrial facilities. Formal CPA work is delivered only through the applicable NEA-accredited verification company; training and research are separately governed.",
  "hero.meeting": "Book a meeting",
  "hero.secondary": "View credentials",
  "credentials.kicker": "Qualifications & Scope",
  "stats.years": "Industrial project experience",
  "stats.roles": "Core regulatory-level qualifications",
  "bridge.copy": "Start with credentials, role boundaries and evidence requirements; then select the right verification, validation, audit, training or research pathway.",
  "credentials.title": "Professional qualifications and delivery boundaries",
  "credentials.copy": "Selected personnel qualifications and programme roles are shown upfront. They do not represent organizational accreditation of Enerstay. Formal verification, validation, assurance and second/third-party audit work proceeds only after confirming the required accredited entity, authorization scope, competence and independence.",
  "credentials.nea.title": "Personnel qualification: Lead Verifier / Independent Reviewer / Sector 3 Expert",
  "credentials.nea.copy": "Carbon Pricing Act verification competence for work delivered through an NEA-accredited verification company and within that entity's accredited sector scope.",
  "credentials.edb.title": "Personnel qualification: Independent Qualified Endorser (QE) for REG(E)",
  "credentials.edb.copy": "Independent endorsement is undertaken only where programme eligibility, appointment, competence and conflict-of-interest requirements are satisfied.",
  "credentials.bsi.title": "Selected BSI-issued personnel qualifications",
  "credentials.bsi.copy": "Includes ISO 14064 GHG verification, ISO 14068-1 carbon-neutrality verification, net-zero pathway verification and ISAE 3000 assurance training or qualification.",
  "services.kicker": "Core Capabilities",
  "services.title": "Service capabilities",
  "services.carbon.copy": "Organizational GHG, project reductions, product carbon footprint and disclosure-assurance evidence review, focused on boundaries, evidence, sampling and conclusion limits.",
  "services.material.title": "Second/third-party management-system audits",
  "services.material.copy": "Second/third-party audits, supplier audits and findings follow-up for environmental, energy, safety and supply-chain management systems.",
  "services.energy.copy": "Independently assess activity data, emission factors, equipment records, supplier information and review trails against the agreed verification or audit criteria.",
  "services.cta": "Check the applicable pathway",
  "team.kicker": "Team & Role Separation",
  "team.title": "Team and role separation",
  "team.copy": "Enerstay separates principal technical direction, training delivery, audit project coordination and external technical review. Formal assurance, verification, validation and second/third-party audit work starts with conflict-of-interest and role-boundary checks.",
  "team.balance": "Leads compliance control, certification-governance risk review, key-account delivery and cross-border TIC coordination, with senior experience in ISO management-system certification governance, technical review and auditor competence systems.",
  "team.yuanzhe": "Leads technical direction, complex-sector judgement, regulatory authorization boundaries and key deliverable review.",
  "team.zeean": "Leads corporate training, partner certificate courses, learner communication and Enerstay Academy delivery.",
  "team.jiahui": "Leads audit project scheduling, document coordination, client communication and process quality tracking.",
  "team.partner.title": "Certification-body and IMS collaboration network",
  "team.partner.copy": "For China-market IMS, supplier audits and certification-body resources, technical collaboration can be arranged through a confidential partner network; specific partner information is handled under project confidentiality requirements.",
  "cases.title": "Anonymized cases and project experience",
  "cases.copy": "Client names, working papers and project conclusions are not disclosed. The cards retain only sector, scale and capability boundaries to show typical scenarios.",
  "cases.edb.m1": "emission-source / evidence types",
  "cases.edb.m2": "industrial project experience",
  "cases.nea.m1": "Carbon Pricing Act pathway",
  "cases.nea.m2": "semiconductor complex sector",
  "cases.sra.m1": "papers / collaboration outputs",
  "cases.sra.m2": "courses and white papers",
  "cases.edb.copy": "High-GWP gases, abatement equipment, activity data, equipment records, abnormal data and evidence-chain control.",
  "cases.nea.copy": "Emissions reporting, verification evidence review, complex data chains, internal QA/QC, management accountability and independent-review documentation.",
  "cases.sra.title": "University platforms and research knowledge products",
  "cases.sra.copy": "References public directions from platforms such as the CUMT Carbon Neutrality Institute and converts them into courses, paper training, white papers and standards knowledge products.",
  "standards.title": "Standards and frameworks",
  "standards.copy": "Official marks below identify verified qualification or programme sources only. The reference matrix then distinguishes engagement criteria, management-system audit standards, assurance standards, disclosure references, carbon-programme rules and non-certifiable guidance.",
  "standards.iso14064": "Organizational GHG, project reductions, validation / verification",
  "standards.iso14067": "Product carbon footprint, LCA, boundaries, allocation and critical review",
  "standards.iso14068": "Carbon-neutrality claims, net-zero pathways, reduction-first logic and assurance evidence review",
  "standards.systems": "Environmental, occupational health and safety, and energy management-system audits",
  "standards.assurance": "Sustainability disclosure, environmental data controls and report-assurance evidence review",
  "standards.iwa": "EU export chains, net-zero guidance and climate-action training",
  "standards.cta": "Clarify applicable standards",
  "standards.logo.issb": "Sustainability and climate-related disclosure requirements",
  "standards.logo.tnfd": "Nature-related risk and disclosure framework",
  "standards.logo.sasb": "Industry-based sustainability disclosure topics",
  "standards.logo.nea": "Carbon Pricing Act reporting and verification pathway",
  "standards.logo.edb": "Resource efficiency grant evidence and endorsement logic",
  "standards.logo.cdp": "Climate questionnaire and disclosure evidence",
  "standards.logo.sbti": "Science-based target setting references",
  "standards.logo.ghg": "Corporate, Scope 2 and Scope 3 accounting references",
  "standards.logo.verra": "Carbon project validation and verification references",
  "standards.logo.aa": "Stakeholder, materiality and assurance principles",
  "standards.logo.isae3000": "Assurance engagements other than audits or reviews of historical financial information",
  "standards.logo.issa5000": "General requirements for sustainability assurance engagements",
  "standards.logo.gold": "Climate project methodology references",
  "standards.logo.gri": "Impact reporting and sustainability topic references",
  "standards.logo.isoCarbon": "GHG, PCF and carbon-neutrality verification references",
  "standards.logo.isoIms": "Environmental, safety and energy management-system audit references",
  "standards.logo.iwa": "Net-zero and climate-action implementation guidance",
  "standards.boundary.title": "Boundary note",
  "standards.boundary.copy": "Engagement criteria, programme rules and reporting references are identified separately in the contract and report. A name or mark on this page does not imply endorsement of Enerstay. Formal conclusions are issued only through the required authorized or accredited route and within confirmed competence, independence and scope.",
  "standards.sources.title": "Verified qualification and programme sources",
  "standards.sources.nea": "Personnel competence used only through an NEA-accredited verification company and within its accredited sector scope.",
  "standards.sources.edb": "Independent Qualified Endorser role subject to programme appointment, eligibility and independence conditions.",
  "standards.sources.bsi": "Source of selected personnel verifier, auditor, net-zero and assurance qualifications; not an Enerstay organizational certification claim.",
  "standards.references.title": "Applicable criteria and reference map",
  "standards.references.copy": "Standard names are shown as text because standards-owner marks do not themselves evidence certification, authorization or endorsement.",
  "standards.type.criteria": "Engagement criteria",
  "standards.type.audit": "Audit standards",
  "standards.type.assurance": "Assurance standards",
  "standards.type.disclosure": "Disclosure references",
  "standards.type.accounting": "Accounting references",
  "standards.type.programme": "Programme rules",
  "standards.type.guidance": "Guidance / training",
  "standards.ref.ghg": "Organizational inventories and GHG validation / verification. The applicable part and edition are confirmed in the engagement scope.",
  "standards.ref.pcf": "Product carbon footprints and LCA principles, boundaries, allocation, quality and critical-review requirements.",
  "standards.ref.netzero": "Carbon-neutrality claims and transition evidence. PAS 2060 is retained only where the specific legacy or transition context requires it.",
  "standards.ref.ims": "Environmental, occupational health and safety, and energy management-system second/third-party audits, subject to the agreed audit criteria.",
  "standards.ref.assurance": "ISAE 3000 for applicable non-financial assurance engagements; ISSA 5000 for sustainability assurance as adopted and effective in the relevant jurisdiction.",
  "standards.ref.disclosure": "Reporting and disclosure references only. Their use does not mean certification, validation or endorsement by the framework owner.",
  "standards.ref.protocol": "Accounting references used where the reporting programme or client mandate requires them; assurance criteria are separately agreed.",
  "standards.ref.programmes": "Programme methodologies and rules. Formal validation / verification is undertaken only within the programme's approved entity and competence scope.",
  "standards.ref.iwa": "Net-zero and ESG implementation guidance used for learning and pathway design; these documents are not certification standards.",
  "training.title": "Training programs",
  "training.copy": "Enerstay Sustainability Academy uses in-house materials, case exercises, data sheets, report templates and assessment packs for corporate training, partner certificate courses, auditor capability programs and overseas ESG study programs. Courses are not formal verification or assurance conclusions.",
  "training.group1": "Standards and verification courses",
  "training.group2": "Disclosure and ESG courses",
  "training.group3": "Industry practice and partner courses",
  "training.catalog": "View full training catalogue",
  "training.corporate": "Discuss corporate training",
  "training.meta1.label": "Duration",
  "training.meta1.value": "1-2 days",
  "training.meta1.copy": "Most Academy modules can be delivered as intensive workshops or adapted into shorter executive briefings.",
  "training.meta2.label": "Format",
  "training.meta2.value": "Online / onsite / cohort",
  "training.meta2.copy": "Corporate in-house delivery, partner certificate courses, university classes and association cohorts are available.",
  "training.meta3.label": "Schedule",
  "training.meta3.value": "Rolling cohorts",
  "training.meta3.copy": "Public or private cohorts can be scoped by audience, language, sector and assessment requirement.",
  "training.route1.type": "Enerstay-owned",
  "training.route1.title": "Practice-led Academy curriculum",
  "training.route1.copy": "Proprietary modules, evidence worksheets, industrial cases and bilingual cohort delivery.",
  "training.route1.cta": "View Academy courses",
  "training.route2.type": "Online access",
  "training.route2.title": "APEX online learning",
  "training.route2.copy": "Direct access to published ISO management-system, auditor, compliance and quality courses.",
  "training.route2.cta": "Open course links",
  "training.route3.type": "Collaboration",
  "training.route3.title": "Applus+ collaborative cohorts",
  "training.route3.copy": "Selected CBAM and technical cohorts, with delivery, assessment and certificate roles confirmed for each programme.",
  "training.route3.cta": "View collaboration route",
  "training.route4.type": "Standards source",
  "training.route4.title": "PAS and ISO transition reference",
  "training.route4.copy": "BSI is cited as the PAS 2060 publisher and transition source, not as a training partner.",
  "training.route4.cta": "Read the boundary",
  "research.title": "Research and knowledge products",
  "research.copy": "Enerstay Sustainability Academy organizes published and Enerstay-supported research outputs by ESG themes and SDG targets, then translates them into course cases, white papers and practice notes.",
  "research.sdg1.title": "Built environment, LCA and verified decarbonization",
  "research.sdg1.copy": "AI building energy baselines, life-cycle carbon governance and climate-resilient building pathways.",
  "research.sdg1.paper": "2026 · Scientific Reports · AI-enabled energy baselines for verified building decarbonization",
  "research.sdg2.title": "Industrial emissions, Scope 3 and semiconductor gases",
  "research.sdg2.copy": "High-GWP semiconductor abatement, automotive Scope 3 data systems and environmental disclosure analytics.",
  "research.sdg2.paper": "2023 · Processes · Best practices for GHG reduction in Singapore's semiconductor industry",
  "research.sdg3.title": "Education, data intelligence and governance",
  "research.sdg3.copy": "AI teaching evaluation, credit-demand analytics and data literacy for ESG knowledge products.",
  "research.sdg3.paper": "2026 · Scientific Reports · Intelligent evaluation and feedback mechanism",
  "research.sdg4.title": "Applied sustainability and field systems",
  "research.sdg4.copy": "Water-use cultivation, marine ROV systems and technology pathways for resource-intensive sectors.",
  "research.sdg4.paper": "2025 · Notulae Botanicae / Scientific Reports · Field systems and resource efficiency",
  "research.scholarCard": "70+ papers and collaboration outputs",
  "research.scholarCardMeta": "Publication list sorted by latest works",
  "research.catalog": "View research catalogue",
  "research.cumt": "CUMT research direction",
  "research.linkedin": "Enerstay LinkedIn",
  "research.visual.caption": "Evidence-led research and knowledge translation",
  "contact.title": "Contact and meeting request",
  "contact.copy": "Please share sector, location, applicable standard, intended use and timeline by email or meeting request. Enerstay will first check role boundaries, independence requirements and the suitable pathway.",
  "contact.meeting": "Book a meeting",
  "contact.emailCta": "Email enquiry",
  "form.option1": "GHG verification",
  "form.option2": "ISO audit",
  "form.option3": "NEA CPA / MRV",
  "form.option4": "Research program",
  "form.option5": "Training",
  "form.submit": "Prepare email"
});

Object.assign(translations.zh, {
  "catalog.eyebrow": "Enerstay Sustainability Academy",
  "catalog.title": "以实践为核心的碳、MRV 与 ESG 培训课程",
  "catalog.copy": "Enerstay 专属课程来自核查验证、工业 MRV、半导体排放和碳市场实践。每个模块配套自有课件、证据工作表、案例练习、数据表和考核材料。",
  "catalog.cta": "沟通企业班",
  "catalog.back": "返回主页",
  "catalog.stat1": "专属课程模块",
  "catalog.stat2": "标准课程时长",
  "catalog.stat3": "可中英双语授课",
  "catalog.system.kicker": "实践体系",
  "catalog.system.title": "Enerstay 自有教材、案例与证据工具",
  "catalog.system.copy": "课程目录面向企业团队、高校、工业园区和专业协会，可按行业、语言、学员层级和考核要求调整。",
  "catalog.feature1.title": "项目导向案例",
  "catalog.feature1.copy": "练习围绕真实 MRV、证据、声明和行业数据问题展开，而不是泛泛的可持续理论。",
  "catalog.feature2.title": "证据工作表",
  "catalog.feature2.copy": "学员会使用边界图、数据表、证据清单和审阅问题，接近专业项目中的工作方式。",
  "catalog.feature3.title": "考核选项",
  "catalog.feature3.copy": "可按课程设置出席证书；如包含并通过考核，也可安排成就证书。",
  "catalog.feature4.title": "边界清晰",
  "catalog.feature4.copy": "培训用于能力和证据素养训练，不构成正式 verification、validation、audit 或 assurance 结论。",
  "catalog.routes.kicker": "入口与边界",
  "catalog.routes.title": "选择正确的学习路径",
  "catalog.routes.copy": "不同路径对应课程材料归属、学习平台、交付角色和证书含义。培训不构成正式核查、验证、审核或保证结论。",
  "catalog.routes.owned.type": "Enerstay 自有",
  "catalog.routes.owned.title": "Academy 实践课程",
  "catalog.routes.owned.copy": "Enerstay 拥有下方 Academy 目录中的课程设计、案例、工作表和考核材料。",
  "catalog.routes.owned.cta": "浏览自有课程",
  "catalog.routes.online.type": "外部线上交付",
  "catalog.routes.online.title": "APEX 学习平台",
  "catalog.routes.online.copy": "已发布线上课程在 APEX 平台学习，报名、学员账号和学习记录由该平台管理。",
  "catalog.routes.online.cta": "选择线上课程",
  "catalog.routes.partner.type": "合作课程",
  "catalog.routes.partner.title": "Applus+ 合作专班",
  "catalog.routes.partner.copy": "选定 CBAM 和技术项目可按合作方式安排；讲师、品牌、考核及证书签发方在每期方案中确认。",
  "catalog.routes.partner.cta": "查看合作范围",
  "catalog.routes.reference.type": "仅作来源参考",
  "catalog.routes.reference.title": "BSI / PAS 标准沿革",
  "catalog.routes.reference.copy": "BSI 仅作为 PAS 2060 发布方和公开转换信息来源引用，不表示合作、背书或课程关联。",
  "catalog.routes.reference.cta": "查看标准沿革",
  "catalog.online.kicker": "线上学习",
  "catalog.online.title": "直达 APEX 线上课程",
  "catalog.online.copy": "下方链接直接打开 APEX 当前已发布的课程页。课程目录可随新内容发布调整，可用性和完成记录以平台为准。",
  "catalog.online.iso": "ISO 管理体系",
  "catalog.online.audit": "审核员能力",
  "catalog.online.compliance": "合规课程",
  "catalog.online.quality": "质量方法",
  "catalog.online.open": "打开课程",
  "catalog.online.all": "全部已发布课程",
  "catalog.online.browse": "浏览 APEX",
  "catalog.online.esg": "ESG 与可持续目录",
  "catalog.online.platform": "APEX 学习平台",
  "catalog.online.visit": "访问平台",
  "catalog.online.boundary.title": "外部平台边界",
  "catalog.online.boundary.copy": "APEX 链接会打开外部学习环境。课程页、学习记录或平台证书应按该平台所示签发方和条款理解，与 Enerstay 正式核查、验证、审核和保证活动分开。",
  "catalog.group1.kicker": "碳与 MRV 实战",
  "catalog.group1.title": "证据、声明与项目周期课程",
  "catalog.group2.kicker": "行业与技术实战",
  "catalog.group2.title": "专项工业与技术模块",
  "catalog.group3.kicker": "市场与研学实战",
  "catalog.group3.title": "市场机制与跨境学习",
  "course.mrv.title": "Carbon MRV - 监测、报告与核查",
  "course.mrv.copy": "围绕 MRV 周期、活动数据、数据质量、证据缺口、报告错误和第三方核查证据开展实践训练。",
  "course.mrv.audience": "适合 EHS、可持续、设施和碳数据团队。",
  "course.cpd.title": "碳项目开发",
  "course.cpd.copy": "覆盖项目概念、方法学选择、基准线和额外性、项目设计文件、validation 与 verification 阶段。",
  "course.cpd.audience": "适合探索碳项目的项目、可持续和技术团队。",
  "course.claims.title": "碳中和声明 - ISO 14068-1 与 PAS 2060 转换",
  "course.claims.copy": "课程以 ISO 14068-1 为当前核心框架，PAS 2060 仅用于历史声明和转换背景，并覆盖减排优先、声明边界与证据要求。",
  "course.claims.audience": "适合负责气候目标、披露和声明的团队。",
  "course.nze.title": "零碳与净零经济",
  "course.nze.copy": "围绕净零定义、行业路径、政策驱动、碳定价、披露压力和转型风险建立整体认知。",
  "course.nze.audience": "适合管理层、运营团队、董事会和学生群体。",
  "course.semi.title": "半导体与高 GWP 气体排放",
  "course.semi.copy": "聚焦含氟气体、尾气处理核算、工艺排放、设备记录、数据质量和半导体 MRV 证据。",
  "course.semi.audience": "适合半导体和先进制造中的工艺、设施、EHS 与可持续团队。",
  "course.ccus.title": "碳捕集、利用与封存 - CCUS",
  "course.ccus.copy": "介绍捕集、利用和封存路径，难减排行业应用，永久性、核算和核查相关考虑。",
  "course.ccus.audience": "适合工程、运营、战略和可持续专业人员。",
  "course.cofi.title": "碳抵消与碳嵌入",
  "course.cofi.copy": "解释 offsetting、insetting、碳信用质量、完整性风险、价值链行动和减排优先定位。",
  "course.cofi.audience": "适合处理碳声明的可持续、采购和传播团队。",
  "course.cmt.title": "碳市场与交易",
  "course.cmt.copy": "覆盖合规和自愿碳市场、配额、碳信用、登记簿、注销、碳定价和完整性风险；课程不构成金融或投资建议。",
  "course.cmt.audience": "适合可持续、财务、采购和战略团队。",
  "course.imm.title": "中新 ESG 研学与海外沉浸项目",
  "course.imm.copy": "模块化研学项目，把课堂 ESG 与碳概念连接到中国和新加坡供应链、自动化和行业实践场景。",
  "course.imm.audience": "适合希望获得跨境实践认知的企业班和学生团队。",
  "catalog.partner.kicker": "合作课程",
  "catalog.partner.title": "Applus+ 合作路径",
  "catalog.partner.copy": "选定 CBAM 和技术专班可将 Enerstay 实践材料与经确认的 Applus+ 合作安排结合。具体法律实体、讲师角色、课程品牌、考核方式和证书签发方在每期方案中确认。",
  "catalog.partner.management.title": "管理层路径",
  "catalog.partner.management.copy": "CBAM 范围、责任矩阵、转换节点、年度数据日历和管理层监督。",
  "catalog.partner.data.title": "数据与报送路径",
  "catalog.partner.data.copy": "产品路径、嵌入排放数据、源记录、计算控制与申报包。",
  "catalog.partner.qa.title": "QA/QC 路径",
  "catalog.partner.qa.copy": "内部复核、证据缺口测试、纠正行动与模拟核查问题。",
  "catalog.partner.boundary.title": "合作边界",
  "catalog.partner.boundary.copy": "Applus+ 仅在经具体确认的合作培训中呈现；不表示所有 Enerstay 课程均由 Applus+ 背书、认证或交付，也不改变正式项目的独立性控制。",
  "catalog.reference.kicker": "标准沿革",
  "catalog.reference.title": "从 PAS 2060 到 ISO 14068-1",
  "catalog.reference.copy": "PAS 2060:2014 由 BSI 发布，现为已撤销的历史参考。Enerstay 仅引用 BSI 公开转换信息说明标准沿革，不将 BSI 呈现为 Academy 合作方。",
  "catalog.reference.legacy": "历史参考",
  "catalog.reference.legacy.copy": "历史碳中和声明要求和证据背景。",
  "catalog.reference.current": "当前课程核心",
  "catalog.reference.current.copy": "当前用于减排优先碳中和路径和声明证据的国际标准。",
  "catalog.reference.pas": "BSI PAS 2060 标准记录",
  "catalog.reference.iso": "BSI 转换概述",
  "catalog.reference.boundary.title": "不主张关联关系",
  "catalog.reference.boundary.copy": "外部链接仅用于来源可追溯。它们不表示 BSI 对 Enerstay 的赞助、合作、背书或授权。",
  "catalog.cta.kicker": "定制企业班",
  "catalog.cta.title": "为团队组合实践型课程路径",
  "catalog.cta.copy": "Enerstay 可为企业、高校、工业园区和协会组合课程模块。课程可用英文、中文或双语授课，并配套案例练习和考核选项。",
  "catalog.cta.email": "联系培训负责人",
  "catalog.cta.contact": "总部联系"
});

Object.assign(translations.en, {
  "catalog.eyebrow": "Enerstay Sustainability Academy",
  "catalog.title": "Practice-led carbon, MRV and ESG training",
  "catalog.copy": "Enerstay proprietary courses are built from verification, industrial MRV, semiconductor emissions and carbon-market practice. Each module uses in-house slides, evidence worksheets, case exercises, data tables and assessment materials.",
  "catalog.cta": "Discuss a cohort",
  "catalog.back": "Back to main site",
  "catalog.stat1": "proprietary modules",
  "catalog.stat2": "standard course duration",
  "catalog.stat3": "bilingual delivery available",
  "catalog.system.kicker": "Practice System",
  "catalog.system.title": "Enerstay-owned materials, cases and evidence tools",
  "catalog.system.copy": "The catalogue is designed for corporate teams, universities, industrial parks and professional associations. Course materials can be adapted by sector, language, audience seniority and assessment requirement.",
  "catalog.feature1.title": "Project-first cases",
  "catalog.feature1.copy": "Exercises are structured around real MRV, evidence, claim and industry-data questions rather than generic sustainability theory.",
  "catalog.feature2.title": "Evidence worksheets",
  "catalog.feature2.copy": "Participants work with boundary maps, data tables, evidence checklists and review questions similar to professional project settings.",
  "catalog.feature3.title": "Assessment options",
  "catalog.feature3.copy": "Attendance certificates and achievement certificates can be arranged where an assessment is included and passed.",
  "catalog.feature4.title": "Boundary clarity",
  "catalog.feature4.copy": "Training builds capability and evidence literacy; it is not a formal verification, validation, audit or assurance conclusion.",
  "catalog.routes.kicker": "Access & Boundaries",
  "catalog.routes.title": "Choose the right learning route",
  "catalog.routes.copy": "The route determines who owns the materials, where learning takes place, who delivers the cohort and what any certificate represents. Training never constitutes a verification, validation, audit or assurance conclusion.",
  "catalog.routes.owned.type": "Enerstay-owned",
  "catalog.routes.owned.title": "Academy practice curriculum",
  "catalog.routes.owned.copy": "Enerstay owns the course design, cases, worksheets and assessment packs shown in the Academy catalogue below.",
  "catalog.routes.owned.cta": "Browse proprietary modules",
  "catalog.routes.online.type": "External online delivery",
  "catalog.routes.online.title": "APEX learning platform",
  "catalog.routes.online.copy": "Published online courses are accessed on the APEX platform. Enrolment, learner accounts and learning records are handled there.",
  "catalog.routes.online.cta": "Choose an online course",
  "catalog.routes.partner.type": "Collaboration",
  "catalog.routes.partner.title": "Applus+ collaborative cohorts",
  "catalog.routes.partner.copy": "Selected CBAM and technical programmes may be arranged collaboratively. Trainer, branding, assessment and certificate-issuer roles are confirmed per cohort.",
  "catalog.routes.partner.cta": "Review collaboration scope",
  "catalog.routes.reference.type": "Reference only",
  "catalog.routes.reference.title": "BSI / PAS standards lineage",
  "catalog.routes.reference.copy": "BSI is referenced as PAS 2060 publisher and public transition source. This is not a partnership, endorsement or course affiliation.",
  "catalog.routes.reference.cta": "See standards lineage",
  "catalog.online.kicker": "Online Learning",
  "catalog.online.title": "Direct access to APEX courses",
  "catalog.online.copy": "Use the links below to open currently published course pages on APEX. The catalogue may change as new lessons are released; availability and completion records are governed by the platform.",
  "catalog.online.iso": "ISO management systems",
  "catalog.online.audit": "Auditor capability",
  "catalog.online.compliance": "Compliance training",
  "catalog.online.quality": "Quality methods",
  "catalog.online.open": "Open course",
  "catalog.online.all": "All published courses",
  "catalog.online.browse": "Browse APEX",
  "catalog.online.esg": "ESG & sustainability catalogue",
  "catalog.online.platform": "APEX learning platform",
  "catalog.online.visit": "Visit platform",
  "catalog.online.boundary.title": "External-platform boundary",
  "catalog.online.boundary.copy": "APEX links open an external learning environment. A course page, learner record or platform certificate should be read according to the issuer and terms shown there; it is separate from Enerstay's formal verification, validation, audit and assurance activities.",
  "catalog.group1.kicker": "Carbon & MRV Practice",
  "catalog.group1.title": "Evidence, claims and project-cycle courses",
  "catalog.group2.kicker": "Industry & Technology Practice",
  "catalog.group2.title": "Specialised industrial and technology modules",
  "catalog.group3.kicker": "Markets & Immersion Practice",
  "catalog.group3.title": "Market mechanisms and cross-border learning",
  "course.mrv.title": "Carbon MRV - Monitoring, Reporting and Verification",
  "course.mrv.copy": "A practice course on the MRV cycle, activity data, data quality, evidence gaps, reporting errors and third-party verification evidence.",
  "course.mrv.audience": "For EHS, sustainability, facilities and carbon-data teams.",
  "course.cpd.title": "Carbon Project Development",
  "course.cpd.copy": "Covers concept design, methodology selection, baseline and additionality, project design documents, validation and verification stages.",
  "course.cpd.audience": "For project, sustainability and technical staff exploring carbon projects.",
  "course.claims.title": "Carbon Neutrality Claims - ISO 14068-1 and PAS 2060 Transition",
  "course.claims.copy": "Uses ISO 14068-1 as the current course framework and PAS 2060 only for legacy-claim and transition context, with reduction-first logic, claim boundaries and evidence expectations.",
  "course.claims.audience": "For climate, disclosure and management teams responsible for targets and claims.",
  "course.nze.title": "Zero Carbon and Net-Zero Economy",
  "course.nze.copy": "A broad orientation on net-zero definitions, sector pathways, policy drivers, carbon pricing, disclosure pressure and transition risks.",
  "course.nze.audience": "For management, operations, board and student cohorts building net-zero literacy.",
  "course.semi.title": "Semiconductor and High-GWP Gas Emissions",
  "course.semi.copy": "A specialised module on fluorinated gases, abatement accounting, process emissions, equipment records, data quality and semiconductor MRV evidence.",
  "course.semi.audience": "For process, facilities, EHS and sustainability teams in semiconductor and advanced manufacturing.",
  "course.ccus.title": "Carbon Capture, Utilisation and Storage - CCUS",
  "course.ccus.copy": "Introduces capture, utilisation and storage pathways, hard-to-abate sectors, permanence, accounting and verification considerations.",
  "course.ccus.audience": "For engineering, operations, strategy and sustainability professionals.",
  "course.cofi.title": "Carbon Offsetting and Insetting",
  "course.cofi.copy": "Explains offsetting, insetting, credit quality, integrity risks, value-chain action and reduction-first positioning.",
  "course.cofi.audience": "For sustainability, procurement and communications teams handling carbon claims.",
  "course.cmt.title": "Carbon Market and Trading",
  "course.cmt.copy": "Covers compliance and voluntary carbon markets, allowances, credits, registries, retirement, carbon pricing and integrity risks. It is not financial or investment advice.",
  "course.cmt.audience": "For sustainability, finance, procurement and strategy teams.",
  "course.imm.title": "China-Singapore ESG Study and Overseas Immersion",
  "course.imm.copy": "A modular immersion-style programme linking classroom ESG and carbon concepts with supply-chain, automation and industry-practice context across China and Singapore.",
  "course.imm.audience": "For corporate cohorts and student groups seeking practical cross-border exposure.",
  "catalog.partner.kicker": "Collaborative Programmes",
  "catalog.partner.title": "Applus+ collaboration pathway",
  "catalog.partner.copy": "Selected CBAM and technical cohorts may combine Enerstay practice materials with an agreed Applus+ collaboration arrangement. The exact legal entity, trainer roles, course branding, assessment method and certificate issuer are confirmed in the cohort proposal.",
  "catalog.partner.management.title": "Management track",
  "catalog.partner.management.copy": "CBAM scope, responsibility matrix, transition milestones, annual data calendar and management oversight.",
  "catalog.partner.data.title": "Data and reporting track",
  "catalog.partner.data.copy": "Product routes, embedded-emissions data, source records, calculation controls and declaration packs.",
  "catalog.partner.qa.title": "QA/QC track",
  "catalog.partner.qa.copy": "Internal review, evidence-gap testing, corrective actions and simulated verification questions.",
  "catalog.partner.boundary.title": "Collaboration boundary",
  "catalog.partner.boundary.copy": "Applus+ is shown only for specifically agreed collaborative training. It does not imply that every Enerstay course is endorsed, certified or delivered by Applus+, and the training relationship does not alter independence controls for formal engagements.",
  "catalog.reference.kicker": "Standards Lineage",
  "catalog.reference.title": "From PAS 2060 to ISO 14068-1",
  "catalog.reference.copy": "PAS 2060:2014 was published by BSI and is now a withdrawn legacy reference. Enerstay cites BSI's public transition information for standards history only; BSI is not presented as an Academy partner.",
  "catalog.reference.legacy": "Legacy reference",
  "catalog.reference.legacy.copy": "Historical carbon-neutrality claim requirements and evidence context.",
  "catalog.reference.current": "Current course core",
  "catalog.reference.current.copy": "Current international framework used for reduction-first carbon-neutrality pathways and claim evidence.",
  "catalog.reference.pas": "BSI PAS 2060 record",
  "catalog.reference.iso": "BSI transition overview",
  "catalog.reference.boundary.title": "No affiliation claim",
  "catalog.reference.boundary.copy": "Links are supplied for source traceability. They do not indicate sponsorship, partnership, endorsement or authorization of Enerstay by BSI.",
  "catalog.cta.kicker": "Custom Cohorts",
  "catalog.cta.title": "Build a practical course pathway for your team",
  "catalog.cta.copy": "Enerstay can combine modules for corporate teams, universities, industrial parks and associations. Cohorts can be delivered in English, Mandarin or bilingual format, with case exercises and assessment options.",
  "catalog.cta.email": "Email Training Lead",
  "catalog.cta.contact": "General contact"
});

Object.assign(translations.zh, {
  "researchPage.eyebrow": "Enerstay Sustainability Academy",
  "researchPage.title": "按 ESG 与 SDG 主题组织的科研与知识产品",
  "researchPage.copy": "本目录对照 Google Scholar 论文列表，整理公开可查且与 Enerstay 支持相关的论文和知识产品。Enerstay Sustainability Academy 将这些成果转化为课程案例、实践笔记、白皮书和科研训练材料。",
  "researchPage.scholar": "打开 Google Scholar",
  "researchPage.back": "返回主页",
  "researchPage.stat1": "主题分类",
  "researchPage.stat2": "实践转化",
  "researchPage.stat3": "课程与知识产品",
  "researchPage.system.kicker": "知识产品体系",
  "researchPage.system.title": "把发表论文转化为可教学、可训练的实践材料",
  "researchPage.system.copy": "Enerstay Sustainability Academy 按 SDG 目标和 ESG 应用场景整理研究成果，并进一步形成课件、选题图谱、数据练习、讨论笔记和论文训练路径。",
  "researchPage.feature1.title": "SDG 分类",
  "researchPage.feature1.copy": "每篇论文对应清洁能源、可持续城市、负责任生产、气候行动、优质教育和产业创新等实践型 SDG 主题。",
  "researchPage.feature2.title": "ESG 实践笔记",
  "researchPage.feature2.copy": "研究成果被转化为 ESG 数据、MRV、Scope 3、LCA、披露分析、工业减排和教学案例。",
  "researchPage.feature3.title": "论文训练",
  "researchPage.feature3.copy": "Academy 材料可用于选题构建、文献图谱、方法选择、结果解读和审稿意见回应训练。",
  "researchPage.feature4.title": "边界清晰",
  "researchPage.feature4.copy": "知识产品用于教育和科研训练，不替代正式 verification、validation、audit 或 assurance 结论。",
  "researchPage.group1.title": "建筑环境、LCA 与可核证减碳",
  "researchPage.group2.title": "工业排放、Scope 3 与环境披露分析",
  "researchPage.group3.title": "教育、数据智能与应用治理",
  "researchPage.group4.title": "应用可持续与现场系统",
  "researchPage.paper.baseline": "把 AI 能耗基线与建筑减碳可核证路径连接起来，可用于 MRV 证据设计、建筑运营能耗训练和绩效数据练习。",
  "researchPage.paper.dlcg": "连接全生命周期碳、LCA、MRV 和气候韧性建筑的数字治理，可支持 LCA 和建筑环境知识产品。",
  "researchPage.paper.buildingReview": "建筑行业综述，可用于比较排放源、减排抓手和低碳资产政策路径。",
  "researchPage.paper.semi": "总结半导体制造中的高 GWP 气体减排、尾气处理选择和监测逻辑，适合工业 MRV 与高 GWP 培训模块。",
  "researchPage.paper.scope3": "围绕 Scope 3 数据、云平台、分析和机器学习构建跨学科框架，适合供应商数据与价值链练习。",
  "researchPage.paper.disclosure": "使用可解释机器学习识别潜在环境披露操纵，为 ESG 数据治理和披露质量训练提供案例。",
  "researchPage.paper.education": "支持教育公平和 AI 学习分析主题，为 Academy 提供研究设计、数据伦理和智能反馈训练案例。",
  "researchPage.paper.credit": "应用数据科学研究，可转化为负责任分析、需求预测和 ESG 时代商业教育中的治理讨论。",
  "researchPage.paper.cultivation": "支持节水效率、资源管理和 SDG 导向科研训练中的应用农业讨论。",
  "researchPage.paper.rov": "现场系统与智能控制研究，可用于复杂海洋环境、工业安全和技术转化讨论。",
  "researchPage.cta.kicker": "知识产品",
  "researchPage.cta.title": "把论文转化为课程、白皮书和实践笔记",
  "researchPage.cta.copy": "Enerstay Sustainability Academy 可将选定研究包装为选题图谱、文献综述工作坊、数据练习、SDG/ESG 教学案例和论文训练路径，服务高校、专业组织和企业班。",
  "researchPage.cta.email": "联系 Academy",
  "researchPage.cta.linkedin": "关注 Enerstay LinkedIn"
});

Object.assign(translations.en, {
  "researchPage.eyebrow": "Enerstay Sustainability Academy",
  "researchPage.title": "Research and knowledge products by ESG and SDG themes",
  "researchPage.copy": "This catalogue organizes public, sponsor-linked papers and related knowledge products from the Google Scholar publication list. Enerstay Sustainability Academy uses these outputs to build training cases, practice notes, white papers and research literacy materials.",
  "researchPage.scholar": "Open Google Scholar",
  "researchPage.back": "Back to main site",
  "researchPage.stat1": "topic taxonomy",
  "researchPage.stat2": "practice translation",
  "researchPage.stat3": "training and knowledge products",
  "researchPage.system.kicker": "Knowledge System",
  "researchPage.system.title": "From published papers to teachable practice",
  "researchPage.system.copy": "Enerstay Sustainability Academy classifies research by SDG target and ESG use case, then converts selected findings into lecture materials, topic maps, data exercises, discussion notes and publication-training pathways.",
  "researchPage.feature1.title": "SDG classification",
  "researchPage.feature1.copy": "Each paper is mapped to practical SDG clusters such as clean energy, sustainable cities, responsible production, climate action, quality education and industry innovation.",
  "researchPage.feature2.title": "ESG practice notes",
  "researchPage.feature2.copy": "Research outputs are summarized into ESG data, MRV, Scope 3, LCA, disclosure analytics, industrial abatement and training-use cases.",
  "researchPage.feature3.title": "Publication training",
  "researchPage.feature3.copy": "Academy materials can support topic framing, literature mapping, method selection, result interpretation and reviewer-response training.",
  "researchPage.feature4.title": "Boundary clarity",
  "researchPage.feature4.copy": "Knowledge products are educational and research-oriented. They do not replace formal verification, validation, audit or assurance conclusions.",
  "researchPage.group1.title": "Built environment, LCA and verified decarbonization",
  "researchPage.group2.title": "Industrial emissions, Scope 3 and environmental disclosure analytics",
  "researchPage.group3.title": "Education, data intelligence and applied governance",
  "researchPage.group4.title": "Applied sustainability and field systems",
  "researchPage.paper.baseline": "Links AI-based energy baselining with verifiable building decarbonization, useful for MRV evidence design, operational-energy training and building-performance data exercises.",
  "researchPage.paper.dlcg": "Connects whole-life carbon, LCA, MRV and digital governance for climate-resilient buildings, forming a basis for LCA and built-environment knowledge products.",
  "researchPage.paper.buildingReview": "A building-sector review that supports classroom comparison of emission sources, mitigation levers and policy pathways for lower-carbon assets.",
  "researchPage.paper.semi": "Summarizes high-GWP gas reduction, abatement choices and monitoring logic for semiconductor manufacturing; useful for industrial MRV and high-GWP training modules.",
  "researchPage.paper.scope3": "Builds a multidisciplinary framework for Scope 3 data, cloud platforms, analytics and machine learning; suitable for supplier-data and value-chain exercises.",
  "researchPage.paper.disclosure": "Uses interpretable machine learning to flag potential environmental-disclosure manipulation, supporting ESG data governance and disclosure-quality training.",
  "researchPage.paper.education": "Supports education-equity and AI-learning analytics topics, giving the Academy examples for research design, data ethics and intelligent-feedback training.",
  "researchPage.paper.credit": "An applied data-science study that can be translated into responsible analytics, demand prediction and governance discussions for ESG-era business education.",
  "researchPage.paper.cultivation": "Supports water-use efficiency, resource management and applied agriculture discussions in SDG-oriented research training.",
  "researchPage.paper.rov": "A field-system and intelligent-control paper that supports technology-transfer discussion around difficult offshore environments and industrial safety.",
  "researchPage.cta.kicker": "Knowledge Products",
  "researchPage.cta.title": "Translate papers into training, white papers and practice notes",
  "researchPage.cta.copy": "Enerstay Sustainability Academy can package selected research into topic maps, literature-review workshops, data exercises, SDG/ESG teaching cases and publication-training pathways for universities, professional groups and corporate cohorts.",
  "researchPage.cta.email": "Email Academy",
  "researchPage.cta.linkedin": "Follow Enerstay LinkedIn"
});

let activeLanguage = "en";
const languageStorageKey = "enerstay-language-v3";
const toggle = document.querySelector("[data-lang-toggle]");
const langOptions = document.querySelectorAll("[data-lang-option]");
const nodes = document.querySelectorAll("[data-i18n]");
const engagementForm = document.querySelector("[data-engagement-form]");
const siteHeader = document.querySelector(".site-header");
const menuToggle = document.querySelector("[data-menu-toggle]");
const navLinks = document.querySelectorAll(".nav a");

function renderLanguage(language) {
  activeLanguage = language;
  document.documentElement.lang = language === "zh" ? "zh-CN" : "en";
  nodes.forEach((node) => {
    const key = node.dataset.i18n;
    if (translations[language][key]) {
      node.textContent = translations[language][key];
    }
  });
  if (langOptions.length) {
    langOptions.forEach((option) => {
      option.dataset.active = String(option.dataset.langOption === language);
    });
  } else if (toggle) {
    toggle.textContent = language === "zh" ? "EN" : "中";
  }
  localStorage.setItem(languageStorageKey, language);
}

toggle.addEventListener("click", () => {
  renderLanguage(activeLanguage === "zh" ? "en" : "zh");
});

menuToggle?.addEventListener("click", () => {
  const isOpen = siteHeader?.classList.toggle("nav-open") || false;
  menuToggle.setAttribute("aria-expanded", String(isOpen));
});

navLinks.forEach((link) => {
  link.addEventListener("click", () => {
    siteHeader?.classList.remove("nav-open");
    menuToggle?.setAttribute("aria-expanded", "false");
  });
});

engagementForm?.addEventListener("submit", (event) => {
  event.preventDefault();
  const submitButton = engagementForm.querySelector(".form-button");
  submitButton?.setAttribute("aria-busy", "true");
  if (submitButton) {
    submitButton.textContent = activeLanguage === "zh" ? submitButton.dataset.busyZh : submitButton.dataset.busyEn;
  }
  const formData = new FormData(engagementForm);
  const message = [
    "Hello Enerstay, I would like to discuss second/third-party audit, GHG verification / validation, training or research collaboration.",
    `Name: ${formData.get("name") || ""}`,
    `Email: ${formData.get("email") || ""}`,
    `Requirement: ${formData.get("requirement") || ""}`,
    `Project background: ${formData.get("message") || ""}`
  ].join("\n");
  window.location.href = `mailto:enquires@enerstaysustainability.com?subject=${encodeURIComponent("Enerstay engagement request")}&body=${encodeURIComponent(message)}`;
  window.setTimeout(() => {
    submitButton?.setAttribute("aria-busy", "false");
    if (submitButton) {
      submitButton.textContent = activeLanguage === "zh" ? submitButton.dataset.defaultZh : submitButton.dataset.defaultEn;
    }
  }, 900);
});

renderLanguage(localStorage.getItem(languageStorageKey) || "en");
