const translations = {
  zh: {
    "nav.services": "能力",
    "nav.categories": "方向",
    "nav.standards": "标准",
    "nav.training": "培训",
    "nav.cases": "案例",
    "nav.contact": "联系",
    "hero.eyebrow": "工业碳保证 · GHG核查/验证 · 二方/三方审核 · 科研合作",
    "hero.title": "面向工业企业与高校的碳保证、标准审核和科研转化平台",
    "hero.copy": "Enerstay Sustainability 聚焦工业碳保证、GHG verification / validation、ISO 管理体系二方/三方审核、培训课程、数字化 MRV 和科研知识产品。涉及正式核查或保证的项目严格区分培训、准备支持与审核/核查角色。",
    "hero.calendly": "预约沟通",
    "hero.cta": "预约沟通",
    "hero.secondary": "查看能力",
    "stats.years": "工业项目连续经验",
    "stats.papers": "SCI/SSCI 论文与合作成果",
    "stats.standards": "覆盖GHG、ESG、能源与安全标准",
    "intro.kicker": "关于 Enerstay",
    "intro.title": "以工业碳保证、标准审核和科研产品连接低碳转型",
    "intro.copy": "Enerstay Sustainability Pte. Ltd. 注册于新加坡，定位为工业碳保证与专业标准平台，重点发展 NEA CPA readiness、ISO 14064 / 14067、复杂行业高 GWP 气体、CBAM 数据、ESG 环境数据控制、二方/三方审核、高端培训、数字化 MRV、学术发表与标准化知识产品。",
    "founder.kicker": "谁在负责交付",
    "founder.title": "Prof. Dr. Yuanzhe Li 主理",
    "founder.copy": "Enerstay Sustainability 由 Prof. Dr. Yuanzhe Li 主理，连接新加坡碳监管、GHG verification / validation、ISO 管理体系审核、半导体高 GWP 气体与科研训练经验。涉及保证、核查或审核的工作，按独立性、利益冲突和授权范围进行边界管理。",
    "founder.point1": "NEA 碳定价法案相关核查与复杂行业经验",
    "founder.point2": "Applus+ 等企业合作与CBAM培训资源",
    "founder.point3": "SCI、SSCI、ESCI、EI 论文合作与科研训练",
    "founder.linkedin": "LinkedIn",
    "founder.scholar": "Google Scholar",
    "images.energy": "半导体洁净室与高GWP气体管理",
    "images.research": "科研训练与项目答辩",
    "images.training": "低碳能源与实施场景",
    "services.kicker": "Assurance, Training & Knowledge",
    "services.title": "工业碳保证、二方/三方审核与知识产品",
    "services.carbon.title": "GHG 核查/验证与保证准备",
    "services.carbon.copy": "围绕 ISO 14064-1、ISO 14064-2、ISO 14064-3、ISO 14065、ISO 14066 的组织层面 GHG、项目减排量、验证/核查流程、证据抽样、重要性与结论边界开展二方或三方核查相关工作。",
    "services.esg.title": "ESG 环境数据控制与保证准备",
    "services.esg.copy": "聚焦 ISSB / SGX 披露中的环境数据、Scope 3、供应商数据包、证据链、内部控制和保证准备；不在同一项目中同时承担管理决策支持与独立保证结论。",
    "services.energy.title": "工业 MRV 与数字化证据链",
    "services.energy.copy": "建立可核查的监测、报告与验证资料结构，覆盖活动数据、排放因子、设备记录、供应商资料、复核轨迹、异常处理和数字化证据包。",
    "services.material.title": "ISO 管理体系二方/三方审核",
    "services.material.copy": "针对 ISO 14001、ISO 45001、ISO 50001、Responsible Care 14001、ISO 20121 等管理体系开展二方/三方审核、供应商审核、符合性审核、审核发现和改进跟踪。",
    "services.research.title": "科研、白皮书与标准知识产品",
    "services.research.copy": "依托高校科研合作与行业资料库，形成白皮书、行业指南、模板库、培训教材、论文合作和标准化技术文件，服务长期知识订阅和专业培训。",
    "services.training.title": "企业培训与国际研学",
    "services.training.copy": "ISO 14064/14067、NEA CPA、CBAM、SGX/ISSB披露、IASE ESG、ISO 14001:2026、IWA 42/48、半导体高GWP气体和可核查MRV课程。",
    "pricing.kicker": "Engagement Boundary",
    "pricing.title": "先确认角色边界、独立性和工作范围",
    "pricing.copy": "正式接项前，Enerstay 会先确认项目是否属于培训、准备支持、二方审核、三方审核、GHG verification / validation、独立复核或科研合作，并完成利益冲突与独立性判断。",
    "pricing.step1.label": "免费",
    "pricing.step1.title": "初步沟通与角色判断",
    "pricing.step1.copy": "确认行业、标准、目标用途、是否涉及正式保证/核查结论，以及 Enerstay 是否适合承担该角色。",
    "pricing.step2.label": "边界",
    "pricing.step2.title": "明确边界、证据和交付物",
    "pricing.step2.copy": "明确组织/产品/项目边界、标准依据、证据要求、抽样逻辑、交付物和不承担事项。",
    "pricing.step3.label": "独立性",
    "pricing.step3.title": "设置独立性和利益冲突控制",
    "pricing.step3.copy": "对可能进入二方/三方审核、GHG verification、validation 或 assurance 的项目，先确认团队角色隔离、技术复核和结论边界。",
    "pricing.cta": "预约边界沟通",
    "categories.kicker": "学术与项目方向",
    "categories.title": "工业碳保证与知识产品方向",
    "categories.lca.title": "生命周期评价与低碳设计",
    "categories.lca.copy": "围绕 ISO 14067、ISO 14040/14044、EPD/产品数据和供应链资料，建立可审阅、可追溯、可复用的产品碳数据包。",
    "categories.ai.title": "数字化 MRV 与复核轨迹",
    "categories.ai.copy": "围绕 evidence management、evidence trail、supplier portal 和 carbon data platform 建立可追溯的数据流和复核记录。",
    "categories.mrv.title": "MRV 与核查方法体系",
    "categories.mrv.copy": "排放边界、活动数据、证据链、复核台账、重要性判断、抽样逻辑和 verification-ready documentation。",
    "categories.esg.title": "企业 ESG 与气候能力建设",
    "categories.esg.copy": "可持续报告中的环境数据控制、Scope 3、供应商数据保证、上市公司披露准备和内部证据管理培训。",
    "categories.industry.title": "先进制造与半导体减排",
    "categories.industry.copy": "半导体、化工、制造、物流、金属、航空与新能源供应链中的高 GWP 气体、工艺排放、能源记录和复杂边界判断。",
    "categories.translation.title": "高校科研与标准知识转化",
    "categories.translation.copy": "与高校、实验室和行业伙伴形成白皮书、论文、课程、模板、数据库和标准/指南项目，支撑长期知识产品。",
    "standards.kicker": "标准与框架",
    "standards.title": "核查、验证、保证与培训覆盖的标准框架",
    "standards.copy": "官网仅展示能力范围。正式 verification、validation、assurance 或二方/三方审核以授权范围、独立性要求、客户委托、保密协议和适用认可要求为边界；不公开客户底稿。",
    "standards.iso14064": "ISO 14064-1 组织层面 GHG、ISO 14064-2 项目减排量、ISO 14064-3 validation / verification 要求。",
    "standards.iso14067": "产品碳足迹量化、报告、数据质量、边界、分配规则、critical review 和 verification-ready evidence。",
    "standards.iso14068": "碳中和声明、减排优先、抵消使用、声明管理、证据边界和保证准备。",
    "standards.lca": "生命周期评价方法、功能单位、清单分析、影响评价与解释。",
    "standards.pas2080": "建筑与基础设施全生命周期碳管理、低碳设计与价值链协同。",
    "standards.systems": "能源、环境、职业健康安全管理体系二方/三方审核、供应商审核和审核发现跟踪。",
    "standards.disclosure": "气候风险、碳目标、披露问卷、企业减排目标与数据治理。",
    "standards.assurance": "ISSB/SGX 可持续披露、报告保证、重要性议题、利益相关方回应与证据准备。",
    "standards.iwa": "净零指南、气候行动实施框架、组织减排路径和供应链协同训练。",
    "method.kicker": "Delivery Controls",
    "method.title": "从委托边界到证据结论的交付控制",
    "method.copy": "Enerstay 将标准条款、技术判断、证据链、质量复核和独立性控制放在同一流程里，确保二方/三方审核、GHG verification / validation、培训和科研合作之间边界清晰。",
    "method.one.title": "角色与范围确认",
    "method.one.copy": "确认项目性质、适用标准、组织/产品/项目边界、利益冲突和是否能承担独立角色。",
    "method.two.title": "证据与数据控制",
    "method.two.copy": "建立证据索引、活动数据、排放因子、监测计划、供应商资料、复核记录和版本控制。",
    "method.three.title": "核查/审核执行",
    "method.three.copy": "按二方/三方审核、verification、validation 或技术复核程序执行抽样、访谈、记录审阅和发现管理。",
    "method.four.title": "技术复核与结论边界",
    "method.four.copy": "对关键判断、发现关闭、技术复核、声明边界和对外表达进行质量控制。",
    "training.kicker": "培训课程",
    "training.title": "培训课程与能力建设",
    "training.copy": "Enerstay Sustainability Academy 基于自有教材、案例练习、数据表、报告模板与考核材料，为企业、高校、园区和协会提供中英双语课程；课程与 Applus+、NEA CPA、香港 IASE、SGX/ISSB、IWA 等路径衔接，但不等同于正式核查或保证结论。",
    "training.system.kicker": "Enerstay Sustainability Academy",
    "training.system.title": "从政策理解、数据治理到核查/保证准备的课程体系",
    "training.system.copy": "课程分为公开课、企业内训、合作证书课程和专项技术训练四层，可按行业、监管压力、岗位角色和能力目标组合。官网不公开列示具体费用，正式方案以课程人数、语言、场地、考核和课程材料边界确认。",
    "training.lead.training": "培训课程主管",
    "training.lead.audit": "审核项目主管",
    "training.applus.title": "Applus+ CBAM Training 系列",
    "training.applus.copy": "面向欧盟出口链条、钢铝及下游制造供应链，设置管理决策、数据填报、QA/QC 质控三条路径，训练 CBAM 范围判断、嵌入排放、监测计划、证据链、MQCP 和核查问询应对。",
    "training.applus.item1": "管理层：责任矩阵、扩围影响判断、年度准备路线。",
    "training.applus.item2": "数据团队：产品线、活动数据、排放因子和申报资料包。",
    "training.applus.item3": "质控团队：内部审阅、证据缺口识别和模拟核查问题表。",
    "training.nea.title": "NEA CPA 碳定价法案特色课程",
    "training.nea.copy": "针对新加坡 Carbon Pricing Act 下的可报告设施、排放报告、核查准备和管理层责任，结合复杂行业与半导体数据链经验，训练企业把碳税合规做成可审核的内部流程。",
    "training.nea.item1": "边界识别、排放源分类、活动数据和证据留存。",
    "training.nea.item2": "监测计划、内部 QA/QC、第三方核查前资料准备。",
    "training.nea.item3": "复杂行业数据口径、异常处理和管理层汇报。",
    "training.iase.title": "香港 IASE 授权 ESG Level 1 & 2",
    "training.iase.copy": "面向 ESG 基础能力、可持续金融和进阶实务能力建设，覆盖 ESG 原则、风险治理、可持续投资、报告框架、利益相关方沟通和案例测评，可中英双语授课。",
    "training.iase.item1": "Level 1：ESG 基础、术语、市场趋势和基础测评。",
    "training.iase.item2": "Level 2：实务方法、披露实践、案例分析和应用演练。",
    "training.iase.item3": "适合企业 ESG 团队、金融机构、高校和专业团队。",
    "training.sgx.title": "SGX Sustainability Report 两天课程",
    "training.sgx.copy": "围绕 ISSB 要求和新加坡上市公司可持续报告实践，训练治理、战略、风险管理、指标与目标、气候相关披露、数据控制和内部审阅流程。",
    "training.sgx.item1": "第 1 天：ISSB/SGX 框架、重要性议题和披露结构。",
    "training.sgx.item2": "第 2 天：数据表、证据链、董事会汇报和报告审阅。",
    "training.sgx.item3": "可配套企业现有报告差距分析与整改清单。",
    "training.pathway1.title": "标准与核查课程",
    "training.pathway1.copy": "ISO 14064、ISO 14067、ISO 14068、ISO 14001、IWA 42、IWA 48、PAS 2060、PAS 2080 与内部审核训练。",
    "training.pathway2.title": "披露、ESG 与供应链课程",
    "training.pathway2.copy": "ISSB/SGX 披露、IASE ESG、CBAM、供应链碳数据、可持续报告、保证准备和供应商资料包。",
    "training.pathway3.title": "行业与项目实战课程",
    "training.pathway3.copy": "NEA CPA、半导体减排、先进制造、能源效率、REG(E) 项目逻辑、MRV 证据包和管理层汇报。",
    "training.iso.title": "ISO 14064 GHG Verification / Validation",
    "training.iso.copy": "覆盖 ISO 14064-1、14064-2、14064-3 的组织边界、项目减排、validation / verification 流程、抽样、重要性、证据链与发现管理。",
    "training.pcf.title": "ISO14067 产品碳足迹与 LCA",
    "training.pcf.copy": "围绕产品边界、功能单位、活动数据、排放因子、分配规则、报告结构、critical review 和 verification-ready evidence 开展工作坊。",
    "training.netzero.title": "净零排放路径与碳中和报告",
    "training.netzero.copy": "结合 ISO 14068、PAS 2060、IWA 42、碳中和和净零差异，训练声明边界、减排优先、抵消使用和保证准备。",
    "training.semiconductor.title": "半导体与先进制造减排",
    "training.semiconductor.copy": "聚焦 PFC、NF3、N2O 等高 GWP 气体，尾气处理设备、工艺排放、设备记录、碳税合规和 MRV 证据链。",
    "training.esg.title": "ESG 环境数据与披露保证训练",
    "training.esg.copy": "从 ISSB/SGX 环境指标、Scope 3、数据控制、报告框架到保证准备，训练企业形成可复核的披露证据。",
    "training.wsh.title": "环境安全与职业健康课程",
    "training.wsh.copy": "可覆盖 ISO45001、工作场所安全、受限空间作业、应急响应、HAZMAT 与安全管理体系。",
    "training.toolkit.title": "Enerstay 碳数据与报告工具包",
    "training.toolkit.copy": "使用 Enerstay 自有教材、计算表、访谈清单和报告模板，训练团队完成数据收集、边界判断、证据整理和管理层汇报。",
    "training.iwa42.title": "IWA 42 净零指南训练",
    "training.iwa42.copy": "围绕净零原则、组织边界、减排优先、抵消使用、声明管理和路线图治理开展实践型课程。",
    "training.iwa48.title": "IWA 48 气候行动实施课程",
    "training.iwa48.copy": "把组织气候行动、适应与减缓、指标管理、供应链协同和实施路线连接到企业管理流程。",
    "training.iso14001.title": "ISO14001:2026 转版与内审训练",
    "training.iso14001.copy": "针对环境管理体系转版、合规义务、生命周期思维、风险机会、内审计划和整改闭环开展专项训练。",
    "training.cpa.title": "NEA CPA 碳定价法案培训",
    "training.cpa.copy": "围绕新加坡碳税、可报告设施、排放报告、核查准备、复杂行业数据链和管理层责任开展实务课程。",
    "cases.kicker": "项目经验",
    "cases.title": "工业项目经验与匿名化案例",
    "cases.copy": "团队经验覆盖全球头部半导体公司、新加坡大型工业设施、先进制造供应链、行业协会和高校科研平台。以下内容仅按能力和场景描述，客户名称、底稿、项目结论和商业细节均不公开披露。",
    "cases.chip1": "半导体",
    "cases.chip2": "航空制造",
    "cases.chip3": "金属冶炼",
    "cases.chip4": "新能源电池",
    "cases.chip5": "建筑环境",
    "cases.chip6": "废弃物管理",
    "cases.metricYear": "2020至今",
    "cases.metric1": "ISO 14064、碳税与工业MRV经验",
    "cases.metric2": "Applus+等企业合作与培训路径",
    "cases.metric3": "大型半导体与复杂工业场景",
    "cases.edb.title": "全球头部半导体与复杂工业 MRV",
    "cases.edb.copy": "围绕高 GWP 气体、尾气处理设备、活动数据、设备运行记录、排放因子、异常数据和证据链开展核查准备、技术复核和工业 MRV 资料管理。",
    "cases.nea.title": "新加坡碳税与 NEA CPA readiness",
    "cases.nea.copy": "支持可报告设施理解碳定价法案要求、排放报告、verification readiness、复杂行业数据链、内部 QA/QC、管理层责任和独立复核资料准备。",
    "cases.sra.title": "中国矿业大学碳中和研究平台与科研合作",
    "cases.sra.copy": "科研合作方向参考中国矿业大学碳中和研究院等高校平台，聚焦 CCUS、高效碳捕集、二氧化碳利用与封存、碳监测、论文训练、白皮书和标准化知识产品。",
    "research.kicker": "科研与教育",
    "research.title": "以高校实验室、行业伙伴和知识产品支撑科研转化",
    "research.copy": "Enerstay Sustainability Academy 将高校实验室资源、行业伙伴经验和工业碳保证主题转化为白皮书、技术指南、课程教材、论文合作、标准/指南项目和模板数据库。科研合作参考中国矿业大学碳中和研究院等平台公开方向。",
    "research.item1": "以工业碳保证、CCUS、碳捕集与封存、碳监测、Scope 3、CBAM、半导体高GWP气体和AI-MRV为主线组织课程和课题。",
    "research.item2": "形成“技术问题识别、证据链设计、数据治理、模型分析、论文写作、同行评审回应”的科研训练链条。",
    "research.item3": "支持 SCI、SSCI、ESCI、EI 等论文合作、白皮书、行业指南、模板库、培训教材和标准化文件。",
    "research.scholar": "Google Scholar",
    "research.cumt": "中国矿业大学碳中和平台",
    "credentials.kicker": "Licenses & Certifications",
    "credentials.title": "重点专业资质与监管授权",
    "credentials.copy": "这里只展示与保证、核查、验证、二方/三方审核、培训和科研合作直接相关的核心资质，不列出证书号码和授权截止日期。完整证明材料可在项目尽调或合作流程中提供。",
    "credentials.edb.title": "Independent Qualified Endorser for REG(E)",
    "credentials.edb.copy": "可围绕资源效率与减排项目开展技术评估、节能量与排放减量逻辑审阅、MRV 证据包和第三方背书资料准备。",
    "credentials.edb.meaning": "客户意义：支持 REG(E) 等资源效率项目所需的技术背书、证据组织和独立评估材料。",
    "credentials.nea.title": "Accredited Lead Verifier / Independent Reviewer / Semiconductor Complex Sector Expert",
    "credentials.nea.copy": "聚焦新加坡碳定价法案下的排放核查、独立复核和半导体复杂行业技术判断，支持高风险数据与边界问题处理。",
    "credentials.nea.meaning": "客户意义：可把碳税合规、复杂排放源和核查证据链提前做成可核查状态。",
    "credentials.sra.title": "Academic, Applus+ & Standards Collaboration",
    "credentials.sra.copy": "连接中国矿业大学碳中和研究平台、Applus+ 等企业合作资源、ISO/PAS/ISSB/IWA 标准训练和科研/白皮书/模板库输出。",
    "credentials.sra.meaning": "客户意义：将产业数据、标准要求和科研成果转化为培训、白皮书、模板、课程和长期知识产品。",
    "credentials.cat1": "碳、净零与保证",
    "credentials.cat2": "法规、管理体系与 ESG",
    "credentials.cat3": "安全、韧性与专业训练",
    "contact.kicker": "Contact",
    "contact.title": "确认审核、核查、培训或科研合作的下一步",
    "contact.copy": "欢迎说明行业、地区、标准、目标用途和时间线。Enerstay 会先判断角色边界、独立性要求和适用路径，再进入二方/三方审核、GHG verification / validation、培训或科研合作安排。",
    "contact.whatsappLabel": "WhatsApp",
    "contact.phoneLabel": "电话",
    "contact.emailLabel": "邮箱",
    "contact.addressLabel": "地址",
    "form.name": "姓名 / Name",
    "form.email": "邮箱 / Email",
    "form.need": "需求 / Requirement",
    "form.placeholder": "请选择需求类型",
    "form.option1": "GHG verification / validation",
    "form.option2": "ISO 二方/三方审核",
    "form.option3": "NEA CPA / 工业MRV",
    "form.option4": "科研/白皮书/知识产品",
    "form.option5": "企业培训",
    "form.message": "项目背景 / Message",
    "form.submit": "发送联系",
    "footer.copy": "Enerstay Sustainability Pte. Ltd. | 新加坡工业碳保证、GHG核查/验证、二方/三方审核、培训与科研知识平台。"
  },
  en: {
    "nav.services": "Services",
    "nav.categories": "Tracks",
    "nav.standards": "Standards",
    "nav.training": "Training",
    "nav.cases": "Experience",
    "nav.contact": "Contact",
    "hero.eyebrow": "Industrial Carbon Assurance · GHG Verification / Validation · Second/Third-Party Audits · Research",
    "hero.title": "Industrial carbon assurance and standards platform",
    "hero.copy": "Enerstay Sustainability focuses on industrial carbon assurance, GHG verification / validation, ISO management-system second/third-party audits, executive training, digital MRV and research-based knowledge products. Assurance, verification and audit roles are separated from preparation and training work.",
    "hero.calendly": "Book a discussion",
    "hero.cta": "Book a discussion",
    "hero.secondary": "Explore capabilities",
    "stats.years": "Years of industrial project continuity",
    "stats.papers": "SCI/SSCI publications and collaboration outputs",
    "stats.standards": "Carbon, ESG, energy and safety standards",
    "intro.kicker": "About Enerstay",
    "intro.title": "Connecting industrial carbon assurance, standards audits and research products",
    "intro.copy": "Enerstay Sustainability Pte. Ltd. is registered in Singapore and positioned as an industrial carbon assurance and professional standards platform, focusing on NEA CPA readiness, ISO 14064 / 14067, complex-sector high-GWP gases, CBAM data, ESG environmental data controls, second/third-party audits, executive training, digital MRV, publications and standardisation knowledge products.",
    "founder.kicker": "Who Leads The Work",
    "founder.title": "Led by Prof. Dr. Yuanzhe Li",
    "founder.copy": "Enerstay Sustainability is led by Prof. Dr. Yuanzhe Li, connecting Singapore carbon regulation, GHG verification / validation, ISO management-system audits, semiconductor high-GWP gases and research training. Assurance, verification and audit work is controlled by independence, conflict-of-interest and authorization boundaries.",
    "founder.point1": "NEA carbon-pricing verification and complex-sector experience",
    "founder.point2": "Applus+ collaboration and CBAM training resources",
    "founder.point3": "SCI, SSCI, ESCI and EI publication collaboration and research training",
    "founder.linkedin": "LinkedIn",
    "founder.scholar": "Google Scholar",
    "images.energy": "Semiconductor cleanroom and abatement engineering",
    "images.research": "Research training and project defense",
    "images.training": "Low-carbon energy and implementation",
    "services.kicker": "Assurance, Training & Knowledge",
    "services.title": "Industrial carbon assurance, second/third-party audits and knowledge products",
    "services.carbon.title": "GHG Verification, Validation & Assurance Readiness",
    "services.carbon.copy": "Second- or third-party work around ISO 14064-1, ISO 14064-2, ISO 14064-3, ISO 14065 and ISO 14066, covering organizational GHG, project reductions, validation / verification procedures, evidence sampling, materiality and conclusion boundaries.",
    "services.esg.title": "ESG Environmental Data Controls & Assurance Readiness",
    "services.esg.copy": "Focused on environmental data, Scope 3, supplier data packs, evidence chains, internal controls and assurance readiness for ISSB / SGX disclosure; management decision support and independent assurance conclusions are not performed under the same role.",
    "services.energy.title": "Industrial MRV & Digital Evidence Trails",
    "services.energy.copy": "Build verification-ready MRV structures covering activity data, emission factors, equipment records, supplier evidence, evidence trails, exception handling and digital evidence packs.",
    "services.material.title": "ISO Second/Third-Party Management-System Audits",
    "services.material.copy": "Second/third-party audits, supplier audits, conformity audits, findings and follow-up for ISO 14001, ISO 45001, ISO 50001, Responsible Care 14001 and ISO 20121 management systems.",
    "services.research.title": "Research, White Papers & Standards Knowledge Products",
    "services.research.copy": "Transform university and industry collaboration into white papers, industry guides, template libraries, training materials, publication collaboration and standards-oriented technical documents.",
    "services.training.title": "Corporate Training & International Programs",
    "services.training.copy": "Courses cover ISO 14064/14067, NEA CPA, CBAM, SGX/ISSB disclosure, IASE ESG, ISO 14001:2026, IWA 42/48, semiconductor high-GWP gases and verification-ready MRV.",
    "pricing.kicker": "How To Start",
    "pricing.title": "Start with role boundaries, independence and scope",
    "pricing.copy": "Before taking on work, Enerstay clarifies whether the request is training, preparation support, second-party audit, third-party audit, GHG verification / validation, independent review or research collaboration, and checks independence and conflicts of interest.",
    "pricing.step1.label": "Free",
    "pricing.step1.title": "Role and fit check",
    "pricing.step1.copy": "Confirm sector, standard, intended use, whether a formal assurance or verification conclusion is involved, and whether Enerstay can take the role.",
    "pricing.step2.label": "Scoping",
    "pricing.step2.title": "Define boundaries, evidence and deliverables",
    "pricing.step2.copy": "Define organizational, product or project boundaries, applicable standards, evidence requirements, sampling logic, deliverables and exclusions.",
    "pricing.step3.label": "Custom quote",
    "pricing.step3.title": "Set independence and conflict controls",
    "pricing.step3.copy": "For second/third-party audits, GHG verification, validation or assurance-related work, confirm role separation, technical review and conclusion boundaries before engagement.",
    "pricing.cta": "Book a boundary discussion",
    "categories.kicker": "Academic & Project Tracks",
    "categories.title": "Academic and project focus areas",
    "categories.lca.title": "Life Cycle Assessment & Low-Carbon Design",
    "categories.lca.copy": "LCA / PCF research and enterprise application for buildings, infrastructure, mining and materials, including cradle-to-gate and cradle-to-grave boundaries.",
    "categories.ai.title": "AI Building Energy & Carbon Baselines",
    "categories.ai.copy": "Energy baselines, anomaly detection, benchmarking, savings quantification and data models connected to MRV and compliance reporting.",
    "categories.mrv.title": "MRV & Verification Methodology",
    "categories.mrv.copy": "Emission boundaries, activity data, evidence chains, review logs, materiality judgement, sampling logic and verification-ready documentation.",
    "categories.esg.title": "Corporate ESG & Climate Capability",
    "categories.esg.copy": "Sustainability reporting, climate disclosure, green supply chains, listed-company readiness and internal carbon management training.",
    "categories.industry.title": "Advanced Manufacturing & Semiconductor Abatement",
    "categories.industry.copy": "Reduction pathways and engineering plans for semiconductor, aerospace, metal, chemical, battery and waste-management sectors.",
    "categories.translation.title": "Research Commercialization & Translation",
    "categories.translation.copy": "University and industry collaboration that turns evidence packages, PCF/LCA methods, research findings and standards knowledge into reusable papers, templates and training materials.",
    "standards.kicker": "Standards & Frameworks",
    "standards.title": "Standards for verification, validation, assurance and training",
    "standards.copy": "This website presents capability areas only. Formal verification, validation, assurance or second/third-party audit work is bounded by authorization scope, independence requirements, client mandate, NDAs and applicable accreditation requirements; client working papers are not disclosed.",
    "standards.iso14064": "ISO 14064-1 organizational GHG, ISO 14064-2 project reductions and ISO 14064-3 validation / verification requirements.",
    "standards.iso14067": "Product carbon footprint quantification, reporting, data quality, boundaries, allocation, critical review and verification-ready evidence.",
    "standards.iso14068": "Carbon neutrality claims, net-zero pathways, reduction-first principles and residual-emission treatment.",
    "standards.lca": "LCA methodology, functional units, inventory analysis, impact assessment and interpretation.",
    "standards.pas2080": "Whole-life carbon management for buildings and infrastructure, low-carbon design and value-chain collaboration.",
    "standards.systems": "Second/third-party audits, supplier audits and findings follow-up for energy, environmental and occupational health and safety management systems.",
    "standards.disclosure": "Climate risk, carbon targets, disclosure questionnaires, corporate reduction goals and data governance.",
    "standards.assurance": "ISSB/SGX sustainability disclosure, report assurance, materiality topics, stakeholder response and evidence preparation.",
    "standards.iwa": "Net-zero guidance, climate-action implementation, organizational reduction pathways and supply-chain collaboration training.",
    "method.kicker": "How We Work",
    "method.title": "Delivery controls from engagement boundary to evidence conclusion",
    "method.copy": "Enerstay combines standard clauses, technical judgement, evidence chains, quality review and independence controls so that second/third-party audits, GHG verification / validation, training and research collaboration remain clearly separated.",
    "method.one.title": "Diagnosis",
    "method.one.copy": "Define emission boundaries, data sources, energy structure and compliance gaps.",
    "method.two.title": "System Building",
    "method.two.copy": "Set up carbon and energy governance structures, SOPs, monitoring plans and internal review rules.",
    "method.three.title": "Implementation",
    "method.three.copy": "Design decarbonization projects and evaluate savings, emission reductions and government support routes.",
    "method.four.title": "Verification",
    "method.four.copy": "Support third-party certification, report review, outcome retention and the next optimization cycle.",
    "training.kicker": "Training Programs",
    "training.title": "Training programs and capability building",
    "training.copy": "Enerstay Sustainability Academy can customize bilingual programs for companies, universities, industrial parks and research teams using Enerstay's own materials, case exercises, data sheets, report templates and assessment packs. Programs can also connect with Applus+, NEA CPA and Hong Kong IASE partner courses across public classes, in-house training, joint certificates and specialist coaching.",
    "training.system.kicker": "Enerstay Sustainability Academy",
    "training.system.title": "A training system from policy literacy and data governance to verification readiness",
    "training.system.copy": "Programs are organized into public courses, in-house training, partner certificate courses and specialist technical training. They can be combined by sector, regulatory pressure, job role and capability objective. Detailed fees are not listed publicly; formal proposals are scoped by cohort size, language, venue, assessment and course-material boundary.",
    "training.lead.training": "Training Program Lead",
    "training.lead.audit": "Audit Project Lead",
    "training.applus.title": "Applus+ CBAM Training Series",
    "training.applus.copy": "For EU export chains, steel/aluminium and downstream manufacturing suppliers, the series offers management, data reporting and QA/QC tracks covering CBAM scope checks, embedded emissions, monitoring plans, evidence chains, MQCP and verification-question readiness.",
    "training.applus.item1": "Management: responsibility matrix, expansion-impact assessment and annual readiness roadmap.",
    "training.applus.item2": "Data teams: product lines, activity data, emission factors and declaration packs.",
    "training.applus.item3": "QA/QC teams: internal review, evidence-gap checks and simulated verification questions.",
    "training.nea.title": "NEA CPA Carbon Pricing Act Specialist Course",
    "training.nea.copy": "For reportable facilities, emissions reporting, verification readiness and management accountability under Singapore's Carbon Pricing Act, this course uses complex-sector and semiconductor data-chain experience to turn carbon-tax compliance into an auditable internal process.",
    "training.nea.item1": "Boundary identification, emission-source classification, activity data and evidence retention.",
    "training.nea.item2": "Monitoring plans, internal QA/QC and pre-verification documentation.",
    "training.nea.item3": "Complex-sector data positions, exception handling and management reporting.",
    "training.iase.title": "Hong Kong IASE Authorized ESG Level 1 & 2",
    "training.iase.copy": "For ESG foundations, sustainable finance and advanced practitioner capability, covering ESG principles, risk governance, sustainable investment, reporting frameworks, stakeholder communication and case assessment in bilingual delivery.",
    "training.iase.item1": "Level 1: ESG foundations, terminology, market trends and baseline assessment.",
    "training.iase.item2": "Level 2: practitioner methods, disclosure practice, case analysis and applied exercises.",
    "training.iase.item3": "Suitable for corporate ESG teams, financial institutions, universities and professional teams.",
    "training.sgx.title": "Two-Day SGX Sustainability Report Course",
    "training.sgx.copy": "Built around ISSB requirements and SGX sustainability-reporting practice, covering governance, strategy, risk management, metrics and targets, climate disclosure, data controls and internal review workflows.",
    "training.sgx.item1": "Day 1: ISSB/SGX framework, material topics and disclosure structure.",
    "training.sgx.item2": "Day 2: data sheets, evidence chains, board reporting and report review.",
    "training.sgx.item3": "Can include a gap assessment and corrective-action list for existing reports.",
    "training.pathway1.title": "Standards and Verification Courses",
    "training.pathway1.copy": "ISO 14064, ISO 14067, ISO 14068, ISO 14001, IWA 42, IWA 48, PAS 2060, PAS 2080 and internal audit training.",
    "training.pathway2.title": "Disclosure, ESG and Supply-Chain Courses",
    "training.pathway2.copy": "ISSB/SGX disclosure, IASE ESG, CBAM, supply-chain carbon data, sustainability reports, assurance readiness and supplier data packs.",
    "training.pathway3.title": "Industry and Project Practice Courses",
    "training.pathway3.copy": "NEA CPA, semiconductor abatement, advanced manufacturing, energy efficiency, REG(E) project logic, MRV evidence packs and management reporting.",
    "training.iso.title": "ISO 14064 GHG Verification / Validation",
    "training.iso.copy": "Covers ISO 14064-1, 14064-2 and 14064-3, including organizational boundaries, project reductions, validation / verification flow, sampling, materiality, evidence chains and findings management.",
    "training.pcf.title": "ISO14067 Product Carbon Footprint & LCA",
    "training.pcf.copy": "Workshops on product boundaries, functional units, activity data, emission factors, allocation rules, report structure and certification readiness.",
    "training.netzero.title": "Net-Zero Pathways & Carbon Neutrality Reports",
    "training.netzero.copy": "Connects ISO14068, PAS2060, carbon peak, carbon neutrality and net zero into an enterprise roadmap and management plan.",
    "training.semiconductor.title": "Semiconductor & Advanced Manufacturing Abatement",
    "training.semiconductor.copy": "Industry training based on semiconductor exhaust treatment, energy systems, process abatement and carbon-tax compliance experience.",
    "training.esg.title": "ESG Environmental Data & Assurance Readiness Training",
    "training.esg.copy": "From topic identification, metrics and data governance to reporting frameworks and assurance preparation.",
    "training.wsh.title": "Environmental Safety & Occupational Health Courses",
    "training.wsh.copy": "Can cover ISO45001, workplace safety, confined-space operations, emergency response, HAZMAT and safety management systems.",
    "training.toolkit.title": "Enerstay Carbon Data & Reporting Toolkit",
    "training.toolkit.copy": "Uses Enerstay's own manuals, calculators, interview checklists and report templates to train teams on data collection, boundary decisions, evidence control and management reporting.",
    "training.iwa42.title": "IWA 42 Net-Zero Guideline Training",
    "training.iwa42.copy": "Practical training on net-zero principles, organizational boundaries, reduction-first logic, offset use, claims management and roadmap governance.",
    "training.iwa48.title": "IWA 48 Climate Action Implementation Course",
    "training.iwa48.copy": "Connects organizational climate action, adaptation and mitigation, metrics management, supply-chain collaboration and implementation roadmaps to enterprise management processes.",
    "training.iso14001.title": "ISO14001:2026 Transition & Internal Audit Training",
    "training.iso14001.copy": "Specialist training on EMS transition, compliance obligations, life-cycle thinking, risks and opportunities, internal audit planning and corrective-action closure.",
    "training.cpa.title": "NEA CPA Carbon Pricing Act Training",
    "training.cpa.copy": "Practical courses on Singapore carbon tax, reportable facilities, emissions reporting, verification readiness, complex-sector data chains and management accountability.",
    "cases.kicker": "Experience",
    "cases.title": "Industrial experience and anonymized cases",
    "cases.copy": "Experience covers global leading semiconductor companies, major Singapore industrial facilities, advanced manufacturing supply chains, industry associations and university research platforms. The content below is described by capability and scenario only; client names, working papers, conclusions and commercial details remain confidential.",
    "cases.chip1": "Semiconductor",
    "cases.chip2": "Aerospace",
    "cases.chip3": "Metal Smelting",
    "cases.chip4": "New Energy Batteries",
    "cases.chip5": "Built Environment",
    "cases.chip6": "Waste Management",
    "cases.metricYear": "2020-present",
    "cases.metric1": "ISO 14064, carbon-tax and industrial MRV experience",
    "cases.metric2": "Applus+ and enterprise collaboration pathways",
    "cases.metric3": "Large semiconductor and complex-sector scenarios",
    "cases.edb.title": "Global leading semiconductor and complex-sector MRV",
    "cases.edb.copy": "Work involves high-GWP gases, abatement equipment, activity data, equipment operation records, emission factors, abnormal data handling and evidence-chain control for verification readiness and industrial MRV.",
    "cases.nea.title": "Singapore carbon tax and NEA CPA readiness",
    "cases.nea.copy": "Support covers emissions reporting under Singapore's carbon-pricing framework, verification readiness, complex-sector data review and semiconductor emission-source management, improving data quality and audit traceability.",
    "cases.sra.title": "CUMT carbon-neutrality research platform and academic collaboration",
    "cases.sra.copy": "Academic collaboration references public research directions from the China University of Mining and Technology carbon-neutrality platform, including CCUS, efficient carbon capture, CO2 utilization and storage, carbon monitoring, papers, white papers and standards knowledge products.",
    "research.kicker": "Research & Education",
    "research.title": "Research translation backed by university laboratories, industry partners and knowledge products",
    "research.copy": "Enerstay Sustainability Academy converts university laboratory resources, industry partner experience and industrial carbon assurance topics into white papers, technical guides, training materials, publication collaboration, standards/guideline projects and template databases. Academic collaboration references public directions from platforms such as the CUMT Carbon Neutrality Institute.",
    "research.item1": "Organize courses and research topics around industrial carbon assurance, CCUS, carbon capture and storage, carbon monitoring, Scope 3, CBAM, semiconductor high-GWP gases and AI-MRV.",
    "research.item2": "Build a research-training chain from topic design, data governance and modeling to paper writing and reviewer response.",
    "research.item3": "Support SCI, SSCI, ESCI, EI and related publication collaboration, research project management and application translation.",
    "research.scholar": "Google Scholar",
    "research.cumt": "CUMT carbon-neutrality platform",
    "credentials.kicker": "Licenses & Certifications",
    "credentials.title": "Key professional qualifications and regulatory authorizations",
    "credentials.copy": "This section highlights qualifications related to assurance, verification, validation, second/third-party audits, training and academic collaboration. Certificate numbers and authorization expiry dates are not listed publicly; supporting evidence can be provided during due diligence.",
    "credentials.edb.title": "Independent Qualified Endorser for REG(E)",
    "credentials.edb.copy": "Supports technical assessment for resource-efficiency and abatement projects, savings and emissions-reduction logic, government grant submissions and MRV evidence packages.",
    "credentials.edb.meaning": "Client value: supports the technical endorsement and evidence pack required for REG(E) grant applications.",
    "credentials.nea.title": "Accredited Lead Verifier / Independent Reviewer / Semiconductor Complex Sector Expert",
    "credentials.nea.copy": "Focused on emissions verification, independent review and semiconductor complex-sector judgement under Singapore's carbon-pricing framework, especially for high-risk data and boundary issues.",
    "credentials.nea.meaning": "Client value: carbon-tax compliance, complex emission sources and verification evidence can be prepared before verification pressure peaks.",
    "credentials.sra.title": "Academic, Applus+ & Standards Collaboration",
    "credentials.sra.copy": "Connects CUMT carbon-neutrality research resources, Applus+ collaboration, ISO/PAS/ISSB/IWA training and research outputs such as papers, white papers and template libraries.",
    "credentials.sra.meaning": "Client value: one data foundation can support reporting, certification, training and research translation.",
    "credentials.cat1": "Carbon, Net Zero & Assurance",
    "credentials.cat2": "Regulatory, Management Systems & ESG",
    "credentials.cat3": "Safety, Resilience & Professional Training",
    "contact.kicker": "Contact",
    "contact.title": "Clarify the next step for audit, verification, training or research collaboration",
    "contact.copy": "Share your industry, location, applicable standard, intended use and timeline. Enerstay will first check role boundaries, independence and the suitable pathway before arranging second/third-party audit, GHG verification / validation, training or research collaboration.",
    "contact.whatsappLabel": "WhatsApp",
    "contact.phoneLabel": "Phone",
    "contact.emailLabel": "Email",
    "contact.addressLabel": "Address",
    "form.name": "Name",
    "form.email": "Email",
    "form.need": "Requirement",
    "form.placeholder": "Select a requirement",
    "form.option1": "GHG verification / validation",
    "form.option2": "ISO second/third-party audit",
    "form.option3": "NEA CPA / industrial MRV",
    "form.option4": "International research program",
    "form.option5": "Corporate training",
    "form.message": "Project background",
    "form.submit": "Send message",
    "footer.copy": "Enerstay Sustainability Pte. Ltd. | Singapore-based industrial carbon assurance, GHG verification / validation, second/third-party audits, training and research knowledge platform."
  }
};

let activeLanguage = "zh";
const toggle = document.querySelector("[data-lang-toggle]");
const nodes = document.querySelectorAll("[data-i18n]");
const engagementForm = document.querySelector("[data-engagement-form]");
const siteHeader = document.querySelector(".site-header");
const menuToggle = document.querySelector("[data-menu-toggle]");
const navLinks = document.querySelectorAll(".nav a");

function renderLanguage(language) {
  activeLanguage = language;
  document.documentElement.lang = language === "zh" ? "zh-CN" : "en";
  nodes.forEach((node) => {
    const key = node.dataset.i18n;
    if (translations[language][key]) {
      node.textContent = translations[language][key];
    }
  });
  toggle.textContent = language === "zh" ? "EN" : "中";
  localStorage.setItem("enerstay-language", language);
}

toggle.addEventListener("click", () => {
  renderLanguage(activeLanguage === "zh" ? "en" : "zh");
});

menuToggle?.addEventListener("click", () => {
  const isOpen = siteHeader?.classList.toggle("nav-open") || false;
  menuToggle.setAttribute("aria-expanded", String(isOpen));
});

navLinks.forEach((link) => {
  link.addEventListener("click", () => {
    siteHeader?.classList.remove("nav-open");
    menuToggle?.setAttribute("aria-expanded", "false");
  });
});

engagementForm?.addEventListener("submit", (event) => {
  event.preventDefault();
  const submitButton = engagementForm.querySelector(".form-button");
  submitButton?.setAttribute("aria-busy", "true");
  if (submitButton) {
    submitButton.textContent = activeLanguage === "zh" ? submitButton.dataset.busyZh : submitButton.dataset.busyEn;
  }
  const formData = new FormData(engagementForm);
  const message = [
    "Hello Enerstay, I would like to discuss an audit, verification, training or research collaboration.",
    `Name: ${formData.get("name") || ""}`,
    `Email: ${formData.get("email") || ""}`,
    `Requirement: ${formData.get("requirement") || ""}`,
    `Project background: ${formData.get("message") || ""}`
  ].join("\n");
  window.open(`https://wa.me/6586267896?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer");
  window.setTimeout(() => {
    submitButton?.setAttribute("aria-busy", "false");
    if (submitButton) {
      submitButton.textContent = activeLanguage === "zh" ? submitButton.dataset.defaultZh : submitButton.dataset.defaultEn;
    }
  }, 900);
});

renderLanguage(localStorage.getItem("enerstay-language") || "zh");
