const translations = {
  zh: {
    "nav.services": "服务",
    "nav.categories": "方向",
    "nav.standards": "标准",
    "nav.training": "培训",
    "nav.cases": "案例",
    "nav.contact": "咨询",
    "hero.eyebrow": "碳管理 · ESG · 标准稽核 · 科研合作",
    "hero.title": "面向企业与高校的低碳标准咨询和科研转化平台",
    "hero.copy": "Enerstay Sustainability 以标准方法、工程经验和论文训练能力，提供碳盘查、PCF/LCA、ESG 披露、净零路径、ISO 稽核、培训课程与科研合作服务。",
    "hero.calendly": "预约15分钟",
    "hero.cta": "预约咨询",
    "hero.secondary": "查看服务",
    "stats.years": "连续项目经验",
    "stats.papers": "SCI/SSCI 论文与合作成果",
    "stats.standards": "覆盖碳、ESG、能源与安全标准",
    "intro.kicker": "关于 Enerstay",
    "intro.title": "以标准、工程和科研连接低碳转型",
    "intro.copy": "Enerstay Sustainability Pte. Ltd. 注册于新加坡，专注环境、安全与可持续发展管理解决方案。团队具备 ISO14064 Lead Auditor、GHG Manager、新加坡注册 Workplace Safety and Health Officer 等资质，并服务于制造业、半导体、新能源、建筑环境、高校科研与国际研学项目。",
    "founder.kicker": "谁在负责交付",
    "founder.title": "Prof. Dr. Yuanzhe Li 主理",
    "founder.copy": "Enerstay Sustainability 由 Prof. Dr. Yuanzhe Li 主理，连接新加坡碳监管、国际标准审核、半导体减排和科研训练经验。项目通常由本人参与范围界定、方法审核、关键交付物复核与客户沟通。",
    "founder.point1": "NEA 碳定价法案相关核查与复杂行业经验",
    "founder.point2": "EDB REG(E) 资源效率项目背书能力",
    "founder.point3": "SCI、SSCI、ESCI、EI 论文合作与科研训练",
    "founder.linkedin": "LinkedIn",
    "founder.scholar": "Google Scholar",
    "images.energy": "半导体洁净室与减排工程",
    "images.research": "科研训练与项目答辩",
    "images.training": "低碳能源与实施场景",
    "services.kicker": "咨询服务",
    "services.title": "面向企业落地与高校合作的咨询服务",
    "services.carbon.title": "碳盘查、PCF 与 LCA",
    "services.carbon.copy": "组织温室气体盘查、产品碳足迹、生命周期评价、系统边界设定、清单建模、排放因子匹配与报告准备。",
    "services.esg.title": "ESG、气候披露与保证准备",
    "services.esg.copy": "ESG 战略、指标体系、数据治理、TCFD / CDP / SBTi 准备、可持续报告技术审阅与保证性审核前辅导。",
    "services.energy.title": "净零路径与 MRV 体系",
    "services.energy.copy": "碳中和路径、减排项目设计、监测报告核证框架、碳税与能源效率项目、减排量与经济效益评估。",
    "services.material.title": "标准体系与内外部稽核",
    "services.material.copy": "ISO14064、ISO14067、ISO14068、ISO14001、ISO45001、ISO50001 等体系辅导、内审、预审核与整改建议。",
    "services.research.title": "科研与论文合作",
    "services.research.copy": "围绕绿色建筑、AI 能效、LCA/PCF、材料与环境工程开展选题设计、数据分析、论文训练与成果转化支持。",
    "services.training.title": "企业培训与国际研学",
    "services.training.copy": "ISO14064/14067、净零路径、ESG 顾问报告、半导体减碳、职业安全健康与定制科研课程。",
    "pricing.kicker": "如何开始",
    "pricing.title": "先用低门槛方式判断是否匹配",
    "pricing.copy": "项目价格按企业规模、组织边界、数据质量、是否需要第三方认证或政府补助材料而定。正式报价前，Enerstay 会先完成需求判断和范围界定。",
    "pricing.step1.label": "免费",
    "pricing.step1.title": "15 分钟初步沟通",
    "pricing.step1.copy": "确认行业、监管压力、目标时间线和是否适合进入下一步。",
    "pricing.step2.label": "范围界定",
    "pricing.step2.title": "3-5 个工作日形成项目建议",
    "pricing.step2.copy": "输出工作范围、交付物、时间表、资料清单和报价依据。",
    "pricing.step3.label": "定制报价",
    "pricing.step3.title": "按边界、认证和补助路径报价",
    "pricing.step3.copy": "适用于 ISO/GHG/PCF/LCA、REG(E)、NEA 碳税、ESG 保证准备和培训项目。",
    "pricing.cta": "预约范围界定",
    "categories.kicker": "学术与项目方向",
    "categories.title": "学术和项目分类介绍",
    "categories.lca.title": "生命周期评价与低碳设计",
    "categories.lca.copy": "建筑、基础设施、采矿与材料行业的 LCA / PCF 研究与企业应用，覆盖从摇篮到大门、从摇篮到坟墓等系统边界。",
    "categories.ai.title": "AI 建筑能效与碳基线",
    "categories.ai.copy": "能耗基线、异常检测、性能对标、节能量量化，以及与 MRV 和合规报告衔接的数据模型。",
    "categories.mrv.title": "MRV 与核查方法体系",
    "categories.mrv.copy": "排放边界、活动数据、证据链、审计台账、5% materiality 风险控制与核验级报告准备。",
    "categories.esg.title": "企业 ESG 与气候能力建设",
    "categories.esg.copy": "可持续报告、气候信息披露、绿色供应链、上市公司披露准备与企业内部碳管理培训。",
    "categories.industry.title": "先进制造与半导体减排",
    "categories.industry.copy": "半导体、航空、金属、化工、新能源电池与废弃物管理等行业的减排路径与工程化方案。",
    "categories.translation.title": "科研产业化与成果转化",
    "categories.translation.copy": "AI 自审计碳核算平台、PCF/LCA 报告自动化、标准化证据包与绿色结果多场景复用。",
    "standards.kicker": "标准与框架",
    "standards.title": "咨询服务覆盖的标准与框架",
    "standards.copy": "官网仅展示标准能力范围，具体客户数据、项目底稿与认证材料不公开披露。所有项目以客户授权、保密协议和第三方认证要求为边界。",
    "standards.iso14064": "组织层面温室气体盘查、项目减排量、核查与验证准备。",
    "standards.iso14067": "产品碳足迹核算、报告、因子选择、数据质量与第三方认证准备。",
    "standards.iso14068": "碳中和声明、净零路径、减排优先原则与剩余排放处理。",
    "standards.lca": "生命周期评价方法、功能单位、清单分析、影响评价与解释。",
    "standards.pas2080": "建筑与基础设施全生命周期碳管理、低碳设计与价值链协同。",
    "standards.systems": "能源、环境、职业健康安全管理体系内外部审核与整改路径。",
    "standards.disclosure": "气候风险、碳目标、披露问卷、企业减排目标与数据治理。",
    "standards.assurance": "可持续报告保证、重要性议题、利益相关方回应与证据准备。",
    "method.kicker": "工作方法",
    "method.title": "从盘查到实施的闭环方法",
    "method.copy": "Enerstay 将标准稽核、工程诊断、数据核算与项目管理放在同一个流程里，帮助客户建立可追溯、可审核、可迭代的低碳管理体系。",
    "method.one.title": "现状诊断",
    "method.one.copy": "识别排放边界、数据来源、能源结构与合规差距。",
    "method.two.title": "体系建设",
    "method.two.copy": "建立碳排放与能源管理架构、SOP、监测计划与内部审核规则。",
    "method.three.title": "项目落地",
    "method.three.copy": "设计节能减碳方案，评估经济效益、减排量与政府支持路径。",
    "method.four.title": "验证改进",
    "method.four.copy": "支持第三方认证、报告复核、成果固化与下一轮优化。",
    "training.kicker": "培训课程",
    "training.title": "培训课程与能力建设",
    "training.copy": "Enerstay Sustainability Academy 可基于自有教材、案例练习、数据表、报告模板与考核材料，为企业、高校、政府园区或科研团队定制中英双语课程；也可与合作机构共同设计证书、专项训练和研学项目。",
    "training.iso.title": "ISO14064 温室气体盘查与核查",
    "training.iso.copy": "覆盖 Part 1、Part 2、Part 3，包含组织盘查、项目减排、核查流程、抽样、重要性、证据链与审核发现。",
    "training.pcf.title": "ISO14067 产品碳足迹与 LCA",
    "training.pcf.copy": "围绕产品边界、功能单位、活动数据、排放因子、分配规则、报告结构和认证准备开展工作坊。",
    "training.netzero.title": "净零排放路径与碳中和报告",
    "training.netzero.copy": "结合 ISO14068、PAS2060、碳达峰、碳中和和净零排放的差异，形成企业路径图与管理计划。",
    "training.semiconductor.title": "半导体与先进制造减排",
    "training.semiconductor.copy": "基于半导体尾气处理、能源系统、工艺减排与碳税合规经验，设计行业专项培训。",
    "training.esg.title": "ESG 顾问报告与披露训练",
    "training.esg.copy": "从议题识别、指标选取、数据治理、报告框架到保证准备，帮助企业团队形成内部执行能力。",
    "training.wsh.title": "环境安全与职业健康课程",
    "training.wsh.copy": "可覆盖 ISO45001、工作场所安全、受限空间作业、应急响应、HAZMAT 与安全管理体系。",
    "training.toolkit.title": "Enerstay 碳数据与报告工具包",
    "training.toolkit.copy": "使用 Enerstay 自有教材、计算表、访谈清单和报告模板，训练团队完成数据收集、边界判断、证据整理和管理层汇报。",
    "training.iase.title": "IASE Level 1 & Level 2 合作课程",
    "training.iase.copy": "面向可持续金融、ESG 基础能力和进阶顾问能力建设，可结合企业案例、测验和双语工作坊交付。",
    "training.iso14001.title": "ISO14001:2026 转版与内审训练",
    "training.iso14001.copy": "针对环境管理体系转版、合规义务、生命周期思维、风险机会、内审计划和整改闭环开展专项训练。",
    "training.cpa.title": "NEA CPA 碳定价法案培训",
    "training.cpa.copy": "围绕新加坡碳税、可报告设施、排放报告、核查准备、复杂行业数据链和管理层责任开展实务课程。",
    "cases.kicker": "项目经验",
    "cases.title": "成果实施与匿名化案例",
    "cases.copy": "团队曾为新加坡及东南亚大型制造企业与科研机构提供温室气体管理、碳税合规、资源效率项目、减碳方案、内外部稽核和科研成果转化支持。以下内容以能力和成果为主，客户名称与底稿细节不公开披露。",
    "cases.chip1": "半导体",
    "cases.chip2": "航空制造",
    "cases.chip3": "金属冶炼",
    "cases.chip4": "新能源电池",
    "cases.chip5": "建筑环境",
    "cases.chip6": "废弃物管理",
    "cases.metricYear": "2020至今",
    "cases.metric1": "ISO14064 与碳税相关咨询经验",
    "cases.metric2": "资源效率补助与减排项目背书路径",
    "cases.metric3": "可在 NDA 下提供项目范围和交付证据",
    "cases.edb.title": "资源效率补助与减排项目背书",
    "cases.edb.copy": "围绕 REG(E) 相关资源效率项目，协助企业梳理项目边界、基准情景、节能减排逻辑、投资与回收期、MRV 证据包和政府申报材料。",
    "cases.nea.title": "碳税、复杂行业核查与半导体能力",
    "cases.nea.copy": "支持碳定价法案下的排放报告、核查准备、复杂行业数据审阅和半导体相关排放源管理，强化企业内部数据质量和审计可追溯性。",
    "cases.sra.title": "科研、标准与产业协同成果",
    "cases.sra.copy": "将标准方法、工程数据和科研训练连接起来，支持绿色建筑、AI 能源基线、LCA/PCF、材料与环境工程方向的论文合作和应用转化。",
    "research.kicker": "科研与教育",
    "research.title": "围绕 SDG 的科研训练、论文合作与产学研协同",
    "research.copy": "Enerstay Sustainability Academy 牵头科研教育与产学研协同，将可持续发展目标转化为可研究、可验证、可发表、可落地的项目主题，覆盖绿色建筑、能源系统、LCA/PCF、AI 数据分析、材料与环境工程等方向。",
    "research.item1": "以 SDG 4、7、9、11、12、13、17 为主线组织课程、课题和企业实践。",
    "research.item2": "形成“选题设计、数据治理、模型分析、论文写作、同行评审回应”的科研训练链条。",
    "research.item3": "支持 SCI、SSCI、ESCI、EI 等论文合作、科研项目管理与应用场景转化。",
    "research.scholar": "Google Scholar",
    "credentials.kicker": "Licenses & Certifications",
    "credentials.title": "重点专业资质与监管授权",
    "credentials.copy": "这里只展示与咨询服务直接相关的核心资质，不列出证书号码和授权截止日期。完整证明材料可在项目尽调或合作流程中提供。",
    "credentials.edb.title": "Independent Qualified Endorser for REG(E)",
    "credentials.edb.copy": "可支持资源效率与减排项目的技术评估、节能量与排放减量逻辑、政府补助申请材料和项目 MRV 证据包。",
    "credentials.edb.meaning": "客户意义：可直接支持 REG(E) 补贴申请所需的技术背书和证据组织。",
    "credentials.nea.title": "Accredited Lead Verifier / Independent Reviewer / Semiconductor Complex Sector Expert",
    "credentials.nea.copy": "聚焦新加坡碳定价法案下的排放核查、独立复核和半导体复杂行业技术判断，支持高风险数据与边界问题处理。",
    "credentials.nea.meaning": "客户意义：可把碳税合规、复杂排放源和审计证据链提前做成可核查状态。",
    "credentials.sra.title": "Standards, Research & Assurance Capability",
    "credentials.sra.copy": "以 ISO、PAS、ESG 保证和科研产出为基础，连接标准审计、工程实施和论文/项目成果转化。",
    "credentials.sra.meaning": "客户意义：同一套数据可服务报告、认证、培训和科研成果转化。",
    "credentials.cat1": "碳、净零与保证",
    "credentials.cat2": "法规、管理体系与 ESG",
    "credentials.cat3": "安全、韧性与专业训练",
    "contact.kicker": "开始咨询",
    "contact.title": "把下一步减碳、合规或科研合作讲清楚",
    "contact.copy": "欢迎说明你的行业、所在地区、当前需求与目标时间线。Enerstay 可提供初步诊断、项目范围界定、培训方案或合作计划建议。",
    "contact.whatsappLabel": "WhatsApp",
    "contact.phoneLabel": "电话",
    "contact.emailLabel": "邮箱",
    "form.name": "姓名 / Name",
    "form.email": "邮箱 / Email",
    "form.need": "咨询需求 / Requirement",
    "form.placeholder": "请选择咨询需求",
    "form.option1": "碳核算与 ISO 稽核",
    "form.option2": "ESG 与环境安全管理",
    "form.option3": "节能减碳项目",
    "form.option4": "国际科研/研学合作",
    "form.option5": "企业培训",
    "form.message": "项目背景 / Message",
    "form.submit": "发送咨询",
    "footer.copy": "Enerstay Sustainability Pte. Ltd. | 新加坡碳管理、ESG、环境与安全咨询机构。"
  },
  en: {
    "nav.services": "Services",
    "nav.categories": "Tracks",
    "nav.standards": "Standards",
    "nav.training": "Training",
    "nav.cases": "Experience",
    "nav.contact": "Consultation",
    "hero.eyebrow": "Carbon Management · ESG · Standards Audit · Research Collaboration",
    "hero.title": "Low-carbon standards and research translation",
    "hero.copy": "Enerstay Sustainability combines auditable methods, engineering experience and research training to deliver carbon inventory, PCF/LCA, ESG disclosure, net-zero pathways, ISO audit support, training programs and publication collaboration.",
    "hero.calendly": "Book 15 minutes",
    "hero.cta": "Book a consultation",
    "hero.secondary": "Explore services",
    "stats.years": "Years of project continuity",
    "stats.papers": "SCI/SSCI publications and collaboration outputs",
    "stats.standards": "Carbon, ESG, energy and safety standards",
    "intro.kicker": "About Enerstay",
    "intro.title": "Connecting standards, engineering and research for low-carbon transition",
    "intro.copy": "Enerstay Sustainability Pte. Ltd. is registered in Singapore and focuses on environmental, safety and sustainability management solutions. The team holds credentials including ISO14064 Lead Auditor, GHG Manager and Singapore-registered Workplace Safety and Health Officer, serving manufacturing, semiconductor, new energy, built environment, university research and international study programs.",
    "founder.kicker": "Who Leads The Work",
    "founder.title": "Led by Prof. Dr. Yuanzhe Li",
    "founder.copy": "Enerstay Sustainability is led by Prof. Dr. Yuanzhe Li, connecting Singapore carbon regulation, international standards auditing, semiconductor abatement and research training experience. Projects are typically scoped, method-reviewed and quality-checked directly by the principal consultant.",
    "founder.point1": "NEA carbon-pricing verification and complex-sector experience",
    "founder.point2": "EDB REG(E) resource-efficiency endorsement capability",
    "founder.point3": "SCI, SSCI, ESCI and EI publication collaboration and research training",
    "founder.linkedin": "LinkedIn",
    "founder.scholar": "Google Scholar",
    "images.energy": "Semiconductor cleanroom and abatement engineering",
    "images.research": "Research training and project defense",
    "images.training": "Low-carbon energy and implementation",
    "services.kicker": "Consulting Services",
    "services.title": "Consulting services for companies and universities",
    "services.carbon.title": "Carbon Inventory, PCF & LCA",
    "services.carbon.copy": "Organizational GHG inventory, product carbon footprint, life-cycle assessment, boundary setting, inventory modeling, emission-factor matching and report preparation.",
    "services.esg.title": "ESG, Climate Disclosure & Assurance Readiness",
    "services.esg.copy": "ESG strategy, metrics, data governance, TCFD / CDP / SBTi readiness, sustainability-report technical review and pre-assurance coaching.",
    "services.energy.title": "Net-Zero Pathways & MRV Systems",
    "services.energy.copy": "Carbon-neutrality pathways, reduction project design, MRV frameworks, carbon-tax and energy-efficiency projects, reduction and financial-benefit assessment.",
    "services.material.title": "Standards Systems & Internal/External Audits",
    "services.material.copy": "Implementation, internal audit, pre-audit and corrective-action support for ISO14064, ISO14067, ISO14068, ISO14001, ISO45001 and ISO50001.",
    "services.research.title": "Research & Publication Collaboration",
    "services.research.copy": "Topic design, data analysis, paper training and translation support around green buildings, AI energy efficiency, LCA/PCF, materials and environmental engineering.",
    "services.training.title": "Corporate Training & International Programs",
    "services.training.copy": "ISO14064/14067, net-zero pathways, ESG consultant reports, semiconductor decarbonization, occupational safety and customized research courses.",
    "pricing.kicker": "How To Start",
    "pricing.title": "Start with a low-friction fit check",
    "pricing.copy": "Pricing depends on company scale, organizational boundaries, data readiness, third-party certification needs and whether government grant materials are involved. Enerstay first clarifies fit and scope before issuing a formal proposal.",
    "pricing.step1.label": "Free",
    "pricing.step1.title": "15-minute discovery call",
    "pricing.step1.copy": "Confirm sector, regulatory pressure, target timeline and whether the work should move to scoping.",
    "pricing.step2.label": "Scoping",
    "pricing.step2.title": "Project brief in 3-5 business days",
    "pricing.step2.copy": "Define scope, deliverables, timeline, document list and proposal basis.",
    "pricing.step3.label": "Custom quote",
    "pricing.step3.title": "Quoted by boundary, assurance and grant path",
    "pricing.step3.copy": "Suitable for ISO/GHG/PCF/LCA, REG(E), NEA carbon tax, ESG assurance readiness and training projects.",
    "pricing.cta": "Book a scoping call",
    "categories.kicker": "Academic & Project Tracks",
    "categories.title": "Academic and project focus areas",
    "categories.lca.title": "Life Cycle Assessment & Low-Carbon Design",
    "categories.lca.copy": "LCA / PCF research and enterprise application for buildings, infrastructure, mining and materials, including cradle-to-gate and cradle-to-grave boundaries.",
    "categories.ai.title": "AI Building Energy & Carbon Baselines",
    "categories.ai.copy": "Energy baselines, anomaly detection, benchmarking, savings quantification and data models connected to MRV and compliance reporting.",
    "categories.mrv.title": "MRV & Verification Methodology",
    "categories.mrv.copy": "Emission boundaries, activity data, evidence chains, audit trails, 5% materiality risk control and verification-ready reports.",
    "categories.esg.title": "Corporate ESG & Climate Capability",
    "categories.esg.copy": "Sustainability reporting, climate disclosure, green supply chains, listed-company readiness and internal carbon management training.",
    "categories.industry.title": "Advanced Manufacturing & Semiconductor Abatement",
    "categories.industry.copy": "Reduction pathways and engineering plans for semiconductor, aerospace, metal, chemical, battery and waste-management sectors.",
    "categories.translation.title": "Research Commercialization & Translation",
    "categories.translation.copy": "AI-assisted self-auditing carbon accounting, automated PCF/LCA reports, standardized evidence packages and reusable green-result assets.",
    "standards.kicker": "Standards & Frameworks",
    "standards.title": "Standards and frameworks covered",
    "standards.copy": "This website only presents capability areas. Client data, project working papers and certification evidence are not publicly disclosed. All work follows client authorization, NDAs and third-party certification requirements.",
    "standards.iso14064": "Organizational GHG inventories, project emission reductions, validation and verification readiness.",
    "standards.iso14067": "Product carbon footprint calculation, reporting, factor selection, data quality and certification preparation.",
    "standards.iso14068": "Carbon neutrality claims, net-zero pathways, reduction-first principles and residual-emission treatment.",
    "standards.lca": "LCA methodology, functional units, inventory analysis, impact assessment and interpretation.",
    "standards.pas2080": "Whole-life carbon management for buildings and infrastructure, low-carbon design and value-chain collaboration.",
    "standards.systems": "Internal and external audit pathways for energy, environmental and occupational health and safety systems.",
    "standards.disclosure": "Climate risk, carbon targets, disclosure questionnaires, corporate reduction goals and data governance.",
    "standards.assurance": "Sustainability-report assurance, materiality topics, stakeholder response and evidence preparation.",
    "method.kicker": "How We Work",
    "method.title": "A closed-loop method from inventory to implementation",
    "method.copy": "Enerstay combines standards auditing, engineering diagnosis, data accounting and project management into one workflow, helping clients build traceable, auditable and improvable low-carbon management systems.",
    "method.one.title": "Diagnosis",
    "method.one.copy": "Define emission boundaries, data sources, energy structure and compliance gaps.",
    "method.two.title": "System Building",
    "method.two.copy": "Set up carbon and energy governance structures, SOPs, monitoring plans and internal review rules.",
    "method.three.title": "Implementation",
    "method.three.copy": "Design decarbonization projects and evaluate savings, emission reductions and government support routes.",
    "method.four.title": "Verification",
    "method.four.copy": "Support third-party certification, report review, outcome retention and the next optimization cycle.",
    "training.kicker": "Training Programs",
    "training.title": "Training programs and capability building",
    "training.copy": "Enerstay Sustainability Academy can customize bilingual programs for companies, universities, industrial parks and research teams using Enerstay's own training materials, case exercises, data sheets, report templates and assessment packs. Joint certificate, specialist and study programs can also be designed with partners.",
    "training.iso.title": "ISO14064 GHG Inventory & Verification",
    "training.iso.copy": "Covers Part 1, Part 2 and Part 3, including organizational inventory, project reductions, verification flow, sampling, materiality, evidence chains and findings.",
    "training.pcf.title": "ISO14067 Product Carbon Footprint & LCA",
    "training.pcf.copy": "Workshops on product boundaries, functional units, activity data, emission factors, allocation rules, report structure and certification readiness.",
    "training.netzero.title": "Net-Zero Pathways & Carbon Neutrality Reports",
    "training.netzero.copy": "Connects ISO14068, PAS2060, carbon peak, carbon neutrality and net zero into an enterprise roadmap and management plan.",
    "training.semiconductor.title": "Semiconductor & Advanced Manufacturing Abatement",
    "training.semiconductor.copy": "Industry training based on semiconductor exhaust treatment, energy systems, process abatement and carbon-tax compliance experience.",
    "training.esg.title": "ESG Consultant Report & Disclosure Training",
    "training.esg.copy": "From topic identification, metrics and data governance to reporting frameworks and assurance preparation.",
    "training.wsh.title": "Environmental Safety & Occupational Health Courses",
    "training.wsh.copy": "Can cover ISO45001, workplace safety, confined-space operations, emergency response, HAZMAT and safety management systems.",
    "training.toolkit.title": "Enerstay Carbon Data & Reporting Toolkit",
    "training.toolkit.copy": "Uses Enerstay's own manuals, calculators, interview checklists and report templates to train teams on data collection, boundary decisions, evidence control and management reporting.",
    "training.iase.title": "IASE Level 1 & Level 2 Partner Courses",
    "training.iase.copy": "Designed for sustainable finance, ESG foundations and advanced advisory capability, with company cases, quizzes and bilingual workshops.",
    "training.iso14001.title": "ISO14001:2026 Transition & Internal Audit Training",
    "training.iso14001.copy": "Specialist training on EMS transition, compliance obligations, life-cycle thinking, risks and opportunities, internal audit planning and corrective-action closure.",
    "training.cpa.title": "NEA CPA Carbon Pricing Act Training",
    "training.cpa.copy": "Practical courses on Singapore carbon tax, reportable facilities, emissions reporting, verification readiness, complex-sector data chains and management accountability.",
    "cases.kicker": "Experience",
    "cases.title": "Implemented outcomes and anonymized cases",
    "cases.copy": "The team has supported major manufacturers and research organizations in Singapore and Southeast Asia with GHG management, carbon-tax compliance, resource-efficiency projects, abatement plans, internal and external audits, and research translation. The content below focuses on capabilities and outcomes while client names and working papers remain confidential.",
    "cases.chip1": "Semiconductor",
    "cases.chip2": "Aerospace",
    "cases.chip3": "Metal Smelting",
    "cases.chip4": "New Energy Batteries",
    "cases.chip5": "Built Environment",
    "cases.chip6": "Waste Management",
    "cases.metricYear": "2020-present",
    "cases.metric1": "ISO14064 and carbon-tax consulting experience",
    "cases.metric2": "Resource-efficiency grant and abatement endorsement pathway",
    "cases.metric3": "Project scope and delivery evidence available under NDA",
    "cases.edb.title": "Resource-efficiency grants and abatement project endorsement",
    "cases.edb.copy": "For REG(E)-related resource-efficiency projects, support includes project boundaries, baseline scenarios, energy and emissions logic, investment payback, MRV evidence packs and government submission materials.",
    "cases.nea.title": "Carbon tax, complex-sector verification and semiconductor capability",
    "cases.nea.copy": "Support covers emissions reporting under Singapore's carbon-pricing framework, verification readiness, complex-sector data review and semiconductor emission-source management, improving data quality and audit traceability.",
    "cases.sra.title": "Research, standards and industry collaboration outputs",
    "cases.sra.copy": "Standards methods, engineering data and research training are connected to support publications and applied translation across green buildings, AI energy baselines, LCA/PCF, materials and environmental engineering.",
    "research.kicker": "Research & Education",
    "research.title": "SDG-oriented research training, publication collaboration and industry-university partnership",
    "research.copy": "Led by Enerstay Sustainability Academy, this work translates the Sustainable Development Goals into researchable, verifiable, publishable and deployable project themes across green buildings, energy systems, LCA/PCF, AI data analytics, materials and environmental engineering.",
    "research.item1": "Organize courses, research topics and enterprise practice around SDG 4, 7, 9, 11, 12, 13 and 17.",
    "research.item2": "Build a research-training chain from topic design, data governance and modeling to paper writing and reviewer response.",
    "research.item3": "Support SCI, SSCI, ESCI, EI and related publication collaboration, research project management and application translation.",
    "research.scholar": "Google Scholar",
    "credentials.kicker": "Licenses & Certifications",
    "credentials.title": "Key professional qualifications and regulatory authorizations",
    "credentials.copy": "This section highlights core qualifications directly related to consulting services. Certificate numbers and authorization expiry dates are not listed publicly; full supporting evidence can be provided during project due diligence or collaboration review.",
    "credentials.edb.title": "Independent Qualified Endorser for REG(E)",
    "credentials.edb.copy": "Supports technical assessment for resource-efficiency and abatement projects, savings and emissions-reduction logic, government grant submissions and MRV evidence packages.",
    "credentials.edb.meaning": "Client value: supports the technical endorsement and evidence pack required for REG(E) grant applications.",
    "credentials.nea.title": "Accredited Lead Verifier / Independent Reviewer / Semiconductor Complex Sector Expert",
    "credentials.nea.copy": "Focused on emissions verification, independent review and semiconductor complex-sector judgement under Singapore's carbon-pricing framework, especially for high-risk data and boundary issues.",
    "credentials.nea.meaning": "Client value: carbon-tax compliance, complex emission sources and audit evidence can be prepared before verification pressure peaks.",
    "credentials.sra.title": "Standards, Research & Assurance Capability",
    "credentials.sra.copy": "Connects standards auditing, engineering implementation and publication or project translation through ISO, PAS, ESG assurance and research outputs.",
    "credentials.sra.meaning": "Client value: one data foundation can support reporting, certification, training and research translation.",
    "credentials.cat1": "Carbon, Net Zero & Assurance",
    "credentials.cat2": "Regulatory, Management Systems & ESG",
    "credentials.cat3": "Safety, Resilience & Professional Training",
    "contact.kicker": "Start A Consultation",
    "contact.title": "Clarify your next step in decarbonization, compliance or research collaboration",
    "contact.copy": "Share your industry, location, current requirement and target timeline. Enerstay can provide initial diagnosis, project scoping, training proposals or collaboration planning.",
    "contact.whatsappLabel": "WhatsApp",
    "contact.phoneLabel": "Phone",
    "contact.emailLabel": "Email",
    "form.name": "Name",
    "form.email": "Email",
    "form.need": "Requirement",
    "form.placeholder": "Select a requirement",
    "form.option1": "Carbon accounting and ISO audit",
    "form.option2": "ESG, environment and safety management",
    "form.option3": "Energy and emission reduction project",
    "form.option4": "International research program",
    "form.option5": "Corporate training",
    "form.message": "Project background",
    "form.submit": "Send enquiry",
    "footer.copy": "Enerstay Sustainability Pte. Ltd. | Singapore-based carbon, ESG, environmental and safety consulting."
  }
};

let activeLanguage = "zh";
const toggle = document.querySelector("[data-lang-toggle]");
const nodes = document.querySelectorAll("[data-i18n]");
const consultationForm = document.querySelector("[data-consultation-form]");
const siteHeader = document.querySelector(".site-header");
const menuToggle = document.querySelector("[data-menu-toggle]");
const navLinks = document.querySelectorAll(".nav a");

function renderLanguage(language) {
  activeLanguage = language;
  document.documentElement.lang = language === "zh" ? "zh-CN" : "en";
  nodes.forEach((node) => {
    const key = node.dataset.i18n;
    if (translations[language][key]) {
      node.textContent = translations[language][key];
    }
  });
  toggle.textContent = language === "zh" ? "EN" : "中";
  localStorage.setItem("enerstay-language", language);
}

toggle.addEventListener("click", () => {
  renderLanguage(activeLanguage === "zh" ? "en" : "zh");
});

menuToggle?.addEventListener("click", () => {
  const isOpen = siteHeader?.classList.toggle("nav-open") || false;
  menuToggle.setAttribute("aria-expanded", String(isOpen));
});

navLinks.forEach((link) => {
  link.addEventListener("click", () => {
    siteHeader?.classList.remove("nav-open");
    menuToggle?.setAttribute("aria-expanded", "false");
  });
});

consultationForm?.addEventListener("submit", (event) => {
  event.preventDefault();
  const submitButton = consultationForm.querySelector(".form-button");
  submitButton?.setAttribute("aria-busy", "true");
  if (submitButton) {
    submitButton.textContent = activeLanguage === "zh" ? submitButton.dataset.busyZh : submitButton.dataset.busyEn;
  }
  const formData = new FormData(consultationForm);
  const message = [
    "Hello Enerstay, I would like to start a consultation.",
    `Name: ${formData.get("name") || ""}`,
    `Email: ${formData.get("email") || ""}`,
    `Requirement: ${formData.get("requirement") || ""}`,
    `Project background: ${formData.get("message") || ""}`
  ].join("\n");
  window.open(`https://wa.me/6586267896?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer");
  window.setTimeout(() => {
    submitButton?.setAttribute("aria-busy", "false");
    if (submitButton) {
      submitButton.textContent = activeLanguage === "zh" ? submitButton.dataset.defaultZh : submitButton.dataset.defaultEn;
    }
  }, 900);
});

renderLanguage(localStorage.getItem("enerstay-language") || "zh");
